jellyfin/jellyfin-vue

.eslintrc.js, jest.config.js, package.json
Add `eslint-plugin-promise` and set rules for Promise linting.
=> style(eslint): add Promise linting rules

components/LoginForm.vue
Show the following errors when required:
- Server not found
- Incorrect Username/Password
- Bad Request
=> feat(component): Show errors when logging in if required

nuxt.config.ts
added Vuetify primary color as JF accent color & enabled generation of CSS variables following
Vuetify theme
=> feat(nuxt.config.ts): primary color and CSS vars

layouts/default.vue, nuxt.config.ts, plugins/userViewsApi.ts, utils/items.ts
=> Add API wrapper for UserViews and list user libraries in the navigation drawer

components/LoginForm.vue
it follows the use of a similar snackbar in the current web client
=> feat(loginform.vue): using snackbar for login errors

layouts/default.vue
fix typo associated with abef993
=> fix(profilepicture): fix profile picture

.vscode/extensions.json
=> chore(vscode): add recommended VSCode extensions for workspace

.eslintignore, components/LoginForm.vue, components/UserButton.vue, layouts/default.vue, package.json, pages/login.vue
This fixes all the TypeScript linting errors on existing components and files.
We're clean now :)
=> Fix TypeScript issues

pages/library/_viewId.vue
Very limited listview for library items
Please feel free to suggest alternative variable names :p
=> Feat/display library Very basic support for viewing library items

.eslintrc.js, layouts/default.vue, layouts/fullpage.vue, package.json, pages/library/_viewId.vue, pages/login.vue, plugins/imageApi.ts, plugins/itemsApi.ts, plugins/snackbar.ts, plugins/userViewsApi.ts, store/snackbar.ts, types/utils.ts, utils/items.ts, yarn.lock
Added more linting rules (ESLint recommended config used explicitly, eslint-plugin-import, Nuxt resolver for the import checks and TypeScript's recommended config.
Fixed all the resulting issues.
=> Introduce more linting rules and fix the resulting errors

components/LoginForm.vue
When sending the login form, the button is put into a loading state and the form is disabled.
=> feat(loginform.vue): form displays loading hints

components/LoginForm.vue, layouts/error.vue, pages/library/_viewId.vue
This a custom component which display an "alert" icon in orange, with a message below. This message is by default "Not found" and can be customize by passing a `custom-message` prop to the component.
Also, there's a linting fix.
Maybe this could need discussion, as those sort of errors could be handled in another way. Such as with a redirection to a 404 page or something.
Here I used the /library/ page when the given ID is wrong to put it as a POC.
=> "Not found" component

.vscode/settings.json, components/Card.vue, components/HomeSection.vue, layouts/default.vue, locales/en-US.json, locales/fr-FR.json, nuxt.config.ts, package.json, pages/index.vue, pages/library/_viewId.vue, plugins/components/vueperSlides.ts, utils/items.ts, yarn.lock
* Complete rewrite of the Card component with consistent sizing of items based on either the type or a forced shape (passed as a prop)
* Add Vueper Slides to the home screen, replacing v-slide-group
=> feat(card): add cards and proper sliders

components/LoginForm.vue
=> feat(loginform.vue): locale switcher in the login form

.ci/azure-pipelines-build.yml, .ci/azure-pipelines.yml, mixins/imageHelper.ts, pages/item/_itemId.vue
adds `yarn build` to pipeline
Fixes resulting errors
Fixes #49
=> ci(azure): add pipeline for testing

pages/library/_viewId.vue
Those are subjective, but I think they work well on the minimum size of each screen size step.
=> feat(itemid.vue): responsive columns size

components/Card.vue, components/UserButton.vue, pages/library/_viewId.vue
* Use a v-btn for the UserButton
* Fix card shape for Folder items
* Fix the Card component and the library page to allow for navigating through folders
=> Fix multiple small issues around the client

components/LoginForm.vue, components/UserButton.vue, nuxt.config.ts, package.json, plugins/deviceProfile.ts, store/deviceProfile.ts, yarn.lock
Generates:
- deviceId (uses uuid)
- deviceName
- clientName
- clientVersion
to be used for access token
=> feat(deviceprofile): add deviceProfile

components/SeasonTabs.vue, components/TvShows.vue, locales/en-US.json, pages/item/_itemId.vue
=> Feat/(tv shows item details) Add ability to access seasons through item details page

pages/index.vue
Provides default values for home screen (upnext, resume, latestmedia) if the displayPrefrences info
from server is non existent
=> fix(home screen): Fallback for homescreen settings

components/Card.vue, components/HomeSection.vue, components/UserButton.vue, nuxt.config.ts
Mainly meant for quick testing of light themes, currently.
=> feat(theme): add dark theme toggle

components/LoginForm.vue
Add error code 401 for to incorrect username/password (unauthorized)
=> fix(login form): add missing error code

components/Card.vue, locales/en-US.json
Change Subtitle Year for series (Start year - end year)
Movies
- Production Year
TV Shows:
- Production Year - Present      (if still running)
- Production Year - End Year    (if finished)
- Production Year                      (if production year = end year)
=> feat(item card): improve Card Subtitles

nuxt.config.ts
Adds a few more locales from the Weblate translations (Norwegian, Polish, Slovak, Turkish and Simplified Chinese).
=> feat(locale): add more locales

components/SeasonTabs.vue, locales/en-US.json, mixins/timeUtils.ts, pages/item/_itemId/index.vue
Features:
- Adds 'Ends at X:XX' to item details page
Fixes:
- Fixes season tabs not appearing on initial page load
=> Feat/calcEndsAt Add ends at time to the item details page

components/BlurhashImage.vue, components/SkeletonCard.vue, locales/en-US.json, nuxt.config.ts, pages/library/_viewId.vue
Fixes: 
- Progress bar only taking up half width of card
- Adds no items found if no items are in the library
- Fixes TS  errors in nuxt.config.ts
The colors used for the light/dark themes are taken from the default vuetify themes.
=> Fix/(small fixes) Small fixes for Blurhash and TS errors

mixins/__tests__/timeUtils.spec.ts, package.json, yarn.lock
=> test(timeutils): Add test for time Utils mixin

locales/en-US.json, pages/library/_viewId.vue
Adds ability to sort items in library view
=> feat(library view): Sort Items in Library View

.ci/azure-pipelines-build.yml
Adds tasks for logging in and out to Docker Hub to the CI to be able to push the built images.
=> Add docker login and logout to CI

nuxt.config.ts
A quick PR while I figure out the madness of my life :)
=> Add Spanish to i18n locales

assets/global.scss, components/ConnectionMonitor.vue, components/LoginForm.vue, components/UserButton.vue, layouts/default.vue, locales/en-US.json, nuxt.config.ts, package.json, pages/index.vue, pages/item/_itemId/index.vue, pages/library/_viewId.vue, pages/login.vue, pages/person/_itemId/index.vue, plugins/userInit.ts, store/backdrop.ts, store/page.ts, store/snackbar.ts, store/user.ts, store/userViews.ts, vue-shims.d.ts
* Add a icon, informing the user that network connection is down
* Fix an issue where userInit would use an invalid token format ("token-ception", the valid token was contained in another token), leading to a blank screen when refreshing the app while logged in
* Add a server version check to the login flow in order to prepare for the new /users/me endpoint
* Make the scrollbars not look like garbage
=> Offline indicator and various fixes

README.md, schemes/jellyfinScheme.ts
Had some trouble running the app with 10.6 and spend like 2h to understand that the server version is what I was having wrong in my dev configuration. 
Really tricky one to find when the error is suppressed like that. Had to read almost the entire code base to find it.
=> fix(login): show correct error message

.github/workflows/codeql-analysis.yml
Ignores CodeQl analysis of *.md and files in api/*
=> ci(codeql): ignore scanning of generated files

components/RelatedItems.vue, pages/item/_itemId/index.vue
=> Related Items - Fix Missing Props

components/RelatedItems.vue, components/TrackList.vue, components/VideoPlayer.vue, locales/en-US.json, mixins/htmlHelper.ts, pages/genre/_itemId/index.vue, pages/item/_itemId/play.vue, plugins/appInit.ts, plugins/browserDetection.ts, store/backdrop.ts, utils/audioFormats.ts, utils/codecProfiles.ts, utils/hlsFormats.ts, utils/mp4AudioFormats.ts, utils/mp4VideoFormats.ts, utils/transcodingFormats.ts, utils/vpxVideoFormats.ts, utils/webmAudioFormats.ts
This should fix *most* eslint errors
- Adds JSDoc comments for function in TrackList
- Removes `console.warn` in htmlHelper
- Removes console error from genre page, store/backdrop
- Adds relevant JS Doc comments for all functions on playback profile
- Fixes ESLint errors in related items
=> Minor fixes - Fix Most linting issues

store/servers.ts, store/user.ts
=> fix(login redirects): fix not redirecting from login -> select server screen

layouts/default.vue, locales/en-US.json
Also, I think weblate is adding space for indentation while our lint rules remove them. Do you think it'd be possible to fix this?
=> fix(default.vue): dark mode toggle localization

components/HomeSection.vue, components/SkeletonCard.vue, components/SkeletonHomeSection.vue
=> Add Skeleton cards for home sections

components/Card.vue, components/HomeHeader.vue
* Fixes the links to libraries
* Adds a default icon for libraries
* Fixes the starting slide for the header
=> Some small fixes for the home screen

assets/global.scss
=> feat(transitions): add nuxt transitions

pages/item/_itemId/index.vue
=> fix(itemdetails): decrease gap between genre and genre items

components/PersonList.vue
=> fix(personlist): fix duplicate icon and picture in person list

components/Card.vue, components/HomeHeader.vue, pages/genre/_itemId/index.vue, pages/item/_itemId/index.vue
=> fix(card): make button nuxt-link aware

nuxt.config.ts
=> fix(build): remove experimental build options

components/BlurhashImage.vue, components/Card.vue
**Fixes**
The primary image being used for movies in the continue watching/up next instead of the backdrop
**Issues**
The TS comments can be removed when jellyfin/jellyfin#4624 is fixed 
**Dependent on #308**
=> fix(home sections): fix incorrect image type some home sections

mixins/imageHelper.ts
Use window.devicePixelRatio to scale CSS dimensions to match hardware resolution
=> fix(imagehelper): increase quality for loaded images

package.json, pages/settings/logsAndActivity.vue, yarn.lock
small fix for escaping html specials chars from activity name
=> fix(activity name escape): escaped activity name of html specials

.github/workflows/main.yml, jest.config.js
Adds code coverage reporting through Codecov
=> ci: add code coverage report

pages/person/_itemId/index.vue
=> fix(person page): fix itemId must not be null or undefined when an item is not passed

layouts/default.vue
Moves getting of user Views to back to a computed property. 
Broken in #125
=> fix(nav draw): fix no library items showing in nav draw

components/UserButton.vue
=> fix(userbutton): fix text in userbutton overflowing

pages/item/_itemId/index.vue
=> fix(item details): fix #433 - undefined country code

components/RelatedItems.vue, components/UserButton.vue
**Changes**
Remove unnecessary TS comments in UserButton
Fix incorrect item link in related items on Artists Page
=> Fix/artist link - Fix link for artists in related items

locales/en-US.json, pages/settings/logsAndActivity.vue
**Changes**
If Loading:
- Show Nothing
If Loaded & there are results:
- Show Results
If Loaded & no results
- Show message saying no results found
If Error
- Show error message
=> refactor(logs and activity): improve error handling of logs and Activity pages

components/Forms/AddServerForm.vue, locales/en-US.json, store/servers.ts
* Fixes URL with a trailing slash causing all images to not work
* Adds some punctuation to the welcome messages to look better.
=> Fix final slash in URL and add punctuation to welcome banner

components/Item/Card.vue, components/Item/SeasonTabs.vue, components/Layout/HomeHeader/HomeHeaderItems.vue, components/Layout/Images/BlurhashImage.vue
Fix sonarrcloud bug:
- Add missing `alt` to image
=> fix(blurhash iamge): add missing alt to image

components/Players/VideoPlayer.vue
=> fix(playback): fix video not being centered during playback

.yarnclean
This should help us keep development environments lighter
=> chore: add .yarnclean file

components/Item/Card.vue
Add library refresh indicators:
https://user-images.githubusercontent.com/19396809/102949825-7eb77680-44c9-11eb-934f-dd30805fff6e.mp4
(WIP) Add the possibility to trigger library scans
=> Add library scan & refresh indicators

components/Item/Card.vue, locales/en-US.json
Wait for #303 
Improves card subtitles for episodes:
If the card is an episode
- Title: Series Name
- Subtitle: SX EY - Episode Name
All other movies/series/albums... remain unchanged
=> Card Subtitles - Improve card subtitles for episodes

components/Item/Card.vue
=> fix(card): fix card icons not being overlayed

components/Item/Card.vue
=> fix(card): fix card subtitle being undefined if there is no production year

README.md
=> docs(readme): add codecov to readme

layouts/fullpage.vue, nuxt.config.ts, package.json, schemes/jellyfinScheme.ts, store/displayPreferences.ts, yarn.lock
locale detection wasn't fully disabled and so our custom locale assignment was overriden by i18n
It uses the custom method I added to https://github.com/ThibaultNocchi/i18n-module/commit/c3f91e0dcd8a38e3a9a0d2f1f24d54e35c5e6e0b to reset the locale set
fix #494
=> fix: fix locales being detected from browser and being overriden

schemes/jellyfinScheme.ts, store/__tests__/userViews.spec.ts, store/userViews.ts
Adds test to the userviews store
Partially addresses #545
=> test(userviews): add test for userviews store, and clear store on logout

schemes/jellyfinScheme.ts, store/backdrop.ts, store/deviceProfile.ts, store/homeSection.ts, store/index.ts, store/page.ts, store/servers.ts, store/snackbar.ts, store/tvShows.ts, store/user.ts, store/userViews.ts
=> Reset all stores at logout

store/__tests__/deviceProfile.spec.ts
Adds tests for:
- Committing 'SET_PROFILE'
- Committing 'CLEAR_PROFILE'
- dispatching 'setDeviceProfile'
- dispatching 'clearDeviceProfile'
=> test(device profile): add tests for device profile

store/__tests__/page.spec.ts
Adds tests for:
- SET_PAGE_TITLE,
- SET_APPBAR_OPACITY
- SET_NAVDRAWER_VISIBILITY
- CLEAR_PAGE
- setPageTitle
- setAppBarOpacity
- showNavDrawer
- clearPage
=> test(page): add tests for page store

components/Layout/AudioControls.vue, components/Players/PlayerManager.vue, store/playbackManager.ts
Currently implemented controls:
- Space - play/pause
- Right Arrow - skip 15s
- Left Arrow - rewind 15s
=> feat(video playback): add limited keyboard controls for controlling video playback

assets/styles/HomeHeader.scss, components/Buttons/UserButton.vue, components/Item/Card.vue, components/Item/SeasonTabs.vue, components/Layout/AudioControls.vue, components/Layout/Backdrop.vue, components/Layout/HomeHeader/HomeHeaderItems.vue, locales/en-US.json, pages/library/_viewId.vue, utils/items.ts
* Remove the background from the welcome message
* Fix missing editMetadata message in en-US
* Cleanup valid library types for reusability
* Fix undefined user property on UserButton in some cases
* Link episode page from the season tabs instead of playing it
* Use light menu color on cards when in light theme (Needs a light theme PR to properly work, weirdly enough)
* Fix footer color in the full screen player when in light mode
=> Small pre release fixes

store/__tests__/backdrop.spec.ts, store/__tests__/deviceProfile.spec.ts, store/__tests__/page.spec.ts, store/__tests__/snackbar.spec.ts, store/__tests__/userViews.spec.ts, store/backdrop.ts, store/deviceProfile.ts, store/page.ts, store/snackbar.ts, store/userViews.ts
As suggested by ThibaultNocchi
=> refactor(test of stores): use default state inside stores instead of defining it in tests

components/Layout/AudioControls.vue, pages/playback/index.vue
=> fix(playback): fixes uncentered album art on playback page. Fixes #558

assets/global.scss, components/System/AddApiKey.vue, components/Users/UserCard.vue, locales/en-US.json, pages/settings/apikeys.vue, pages/settings/index.vue, pages/settings/logsAndActivity.vue
Adds settings page for adding/deleting/managing API keys
=> feat(apikeys settings): add settings page for managing API keys

components/Players/PlayerManager.vue, store/playbackManager.ts
=> fix: playback reporting when changing index directly

utils/playbackProfiles/directPlayProfile.ts
=> fix(video profiles): fix sending a webM file containing h264 (fixes #586)

store/__tests__/playbackManager.spec.ts, store/playbackManager.ts
Adds tests for playback manager store
Also fixes adding duplicate items to the queue
=> test(playback store): add tests for playback store

components/Players/AudioPlayer.vue, store/playbackManager.ts
Found the real reason for the problem we were facing, so removed the hack and handling this properly now.
This also fixes #495
=> fix(playbackmanager): remove hack for keeping status as playing

pages/item/_itemId/index.vue
=> fix(item): add bottom margin to play button

layouts/default.vue
Only on larger layouts
https://user-images.githubusercontent.com/10274099/105354227-8b2a0e80-5bf0-11eb-9c9d-4ba070bc6f78.mp4
=> feat: expand search textfield when active

components/Item/Card.vue
* Fixes item menu longside play button introduced in #609 
* Removes the like button from library cards
=> fix: button positioning and fav in libraries

nuxt.config.ts
A bit of polish to the loading in static mode.
https://user-images.githubusercontent.com/19396809/106005393-7a780d80-60b4-11eb-9c3f-79eb620003c8.mp4
=> feat(loading): add loading indicator colors

components/Layout/AudioControls.vue, layouts/default.vue, pages/fullscreen/playback/index.vue
=> fix: misc fixes (fullscreen playback, styling, layout, etc...)

.eslintrc.js, components/Buttons/FilterButton.vue, components/Forms/AddServerForm.vue, components/Forms/LoginForm.vue, components/Item/Metadata/DateInput.vue, components/Item/Metadata/ImageEditor.vue, components/Item/Metadata/ImageSearch.vue, components/Item/Metadata/MetadataEditor.vue, components/Item/Metadata/MetadataEditorDialog.vue, components/Item/Metadata/PersonEditor.vue, components/Layout/HomeHeader/HomeHeaderItems.vue, components/Layout/HomeHeader/SwiperProgressBar.vue, components/Layout/Images/BlurhashImage.vue, components/Layout/VolumeSlider.vue, components/Players/AudioPlayer.vue, components/Players/TrackList.vue, components/Wizard/WizardAdminAccount.vue, layouts/default.vue, package.json, pages/artist/_itemId/index.vue, pages/item/_itemId/index.vue, pages/metadata/index.vue, pages/settings/logsAndActivity.vue, pages/wizard.vue, yarn.lock
Correct:
```
<v-divider />
```
Incorrect:
```
<v-divider></v-divider>
```
=> Linting - Add html-self-closing rule

components/Item/Card/Card.vue, components/Skeletons/SkeletonItemGrid.vue, utils/__tests__/items.spec.ts, utils/items.ts
Adds tests for utils/item
Refactors utils/items:
- Extracts duplicate occurrences of functions determining item card shape to item utils
=> Item Utils - Refactor and Add tests

components/Item/Metadata/ImageEditor.vue, components/Item/Metadata/ImageSearch.vue, components/Players/TrackList.vue, locales/en-US.json, pages/item/_itemId/index.vue, pages/person/_itemId/index.vue
Adds translations for the following:
- Birth Place
- Birth
- Title
- Cast
- Crew
Moves imageTypes (backdrop, primary...)
under imagetype
=> Add missing translations

components/Buttons/LikeButton.vue, components/Buttons/__tests__/LikeButton.spec.ts, components/Item/Card/Card.vue, jest.setup.ts
Refactors LikeButton and adds tests
=> Add tests to LikeButton.vue

components/Layout/HomeSection.vue
Remove reference to $fetchstate
=> fix(home sections): fix undefined $fetchstate when loading home sections

plugins/persistedState.ts, schemes/jellyfinScheme.ts
=> fix(server store): fix server store not being persistant

pages/settings/index.vue
=> fix(settings page): fix server info being overlapping

components/System/SelectedDeviceInfo.vue, locales/en-US.json, pages/settings/devices.vue, pages/settings/index.vue, pages/settings/logsAndActivity.vue
**Features**
- Adds a device page to settings.
**Changes**
- Moves 'logsAndActivity' translation keys under 'settings'
<details>
<summary>Large Screens</summary>
</details>
<details>
<summary>Small Screens</summary>
</details>
<details>
<summary>Small Screens - Device Selected</summary>
</details>
=> Feat devices - Add devices page to settings

components/Buttons/UserButton.vue, plugins/persistedState.ts, schemes/jellyfinScheme.ts
This should fix:
- Server store not persisting on http connections
- The stores not being cleared if logout fails
=> Fix server store not persisting on http connections

.eslintrc.js, components/System/DarkModeToggle.vue, components/Wizard/WizardMetadata.vue, pages/item/_itemId/index.vue, pages/settings/logsAndActivity.vue
Thanks @ThibaultNocchi for noticing the rule!
=> Add linting rule for Vue template whitespace

locales/en-US.json
=> fix(locales): fix duplicate of settings object

components/Buttons/UserButton.vue
=> feat: add icons to userbutton

pages/fullscreen/playback/index.vue
Adds an scale transition to the fullscreen music player:
https://user-images.githubusercontent.com/10274099/107555939-11c28200-6bd8-11eb-96c0-0236cc5dc2e2.mp4
=> feat: add scale transition to fullscreen covers

components/Item/Card/Card.vue, components/Item/ItemGrid.vue, components/Layout/SwiperSection.vue, components/Skeletons/SkeletonCard.vue, components/Skeletons/SkeletonHomeSection.vue, components/Skeletons/SkeletonItemGrid.vue, pages/artist/_itemId/index.vue, pages/genre/_itemId/index.vue, pages/item/_itemId/index.vue, pages/musicalbum/_itemId/index.vue, pages/series/_itemId/index.vue
=> Refactor card to use false for default props

components/Item/Card/Card.vue
=> fix(card): fix no images appearing on some cards on home screen

components/Item/Card/Card.vue, components/Layout/AudioControls.vue, components/Layout/HomeHeader/HomeHeaderItems.vue, components/Layout/Images/BlurhashImage.vue, mixins/itemHelper.ts, pages/fullscreen/playback/index.vue
Handle all the icons fallback directly using BlurhashImage, which also takes care of showing logos when there are errors.
=> feat: handle fallbacks in blurhashimage

components/Layout/HomeSection.vue, pages/index.vue, store/homeSection.ts
Home section titles are now reactive to locale changes
=> fix(home sections): fix titles being localized too early to be reactive

locales/en-US.json, pages/library/_viewId.vue
=> fix(library filters): disable library filters when there are no items in library

assets/variables.scss, components/Layout/Images/UserImage.vue
=> feat(light theme): add some light theme colors

assets/global.scss, components/Layout/AudioControls.vue, components/Layout/Backdrop.vue, components/Players/PlayerManager.vue, layouts/default.vue, nuxt.config.ts
This does a few things:
* Fixes the backdrop overlay not over-scrolling properly
* Use a transparent system bar on iOS
* Fix the app bar to display properly with the transparent system bar
* Add safe zones to the various player controls
**iOS 14.4 (iPhone 12)**
*Before*
*after*
=> Improve PWA experience

jest-helpers.d.ts, jest.config.js, store/__tests__/items.spec.ts, store/index.ts, store/items.ts
This PR will migrate our current different stores to a single store for the item storage
Part of #801
Added the HTML and lcov coverage reporters to Jest
=> Add an item store

store/__tests__/items.spec.ts
=> fix: remove .ts extension from item store test

store/plugins/websocket.ts
This adds a mixin to provide real-time updating of items based on notification from the server.
Some parts that can't use the mixin have their own implementation.
https://user-images.githubusercontent.com/19396809/106389561-2c307a80-63e4-11eb-87df-22a4542015ef.mp4
=> Add server-controlled item data updates

.github/workflows/rebase.yml
Team members can type ``@jellyfin rebase`` on any PR for quickly triggering a rebase on that branch
=> ci: add rebase workflow

README.md
=> chore: remove forum badge

.eslintrc.js, package-lock.json, package.json
Enforces the changes added in #725
=> chore(eslint): enforce individual methods on lodash imports

client/components/Buttons/PlayButton.vue
This was removed accidentally in #843
=> feat(play-button): bring back the loading states of the play button

client/nuxt.config.ts, client/plugins/userLibrary.ts
With the item PR, I forgot to `git add` my changes to nuxt.config.ts where I registered the plugin. It's now done
=> fix: items plugin was unregistered

client/assets/global.scss, client/assets/variables.scss, client/nuxt.config.ts, client/pages/settings/index.vue
There were certain changes I made global to apply to all table elements, and others I kept scoped to this specific info element like the bottom border removal.
=> fix(ui): update global style for tables and server info element

client/components/Item/Card/Card.vue, client/components/Item/Metadata/MetadataEditor.vue, client/components/Layout/AudioControls.vue, client/components/Layout/SettingsPage.vue, client/locales/en-US.json, client/pages/artist/_itemId/index.vue, client/pages/item/_itemId/index.vue, client/pages/musicalbum/_itemId/index.vue, client/pages/series/_itemId/index.vue, client/pages/settings/apikeys.vue
This is a bit of a vague pull request but none of these changes seemed large enough to split into a separate branch.
=> fix(ui): miscellaneous string and layout fixes

.github/workflows/rebase.yml
This should (in theory) give some feedback that the comment for rebasing has been seen by the action, but adding :+1: as a reaction to it.
=> ci(rebase): react on comment when rebase starts

client/store/plugins/websocket.ts
=> fix(websocket): fix item updating

client/components/Players/PlayerManager.vue, client/nuxt.config.ts, client/plugins/components/vueFullscreen.ts, package-lock.json, package.json
=> Implement fullscreen video player

client/store/plugins/websocket.ts
Implements the item store for the like button and markplayed button
=> feat(websocket): handle UserDataChanged messages to update the item store

client/components/Layout/SwiperSection.vue
Nothing much to say about this :)
=> feat(homesections): disable the pagination arrows if swiper is at the end or the beginning

client/components/Layout/AudioControls.vue
I was confused the first time I opened the fullscreen page because the button simply disappeared, and I had to search for a bit before remembering the back button exists.
=> fix(ui): slight improvements to audio controls

client/pages/item/_itemId/index.vue, client/pages/musicalbum/_itemId/index.vue, client/pages/series/_itemId/index.vue
=> fix: genre chips margin

client/components/Item/ItemGrid.vue, client/locales/en-US.json, client/pages/artist/_itemId/index.vue
Adds a new tab on the artist details page, which lists the available music videos for that artist.
=> feat(artist): add music video list to artist details page

client/nuxt.config.ts
fix zh-CN & zh-TW display name
=> fix(i18n): lang setting display name

client/assets/global.scss, client/components/Players/PlayerManager.vue, client/layouts/default.vue, client/nuxt.config.ts, client/plugins/directives/hide.ts, client/plugins/playbackPlugin.ts, client/store/items.ts
* Added a ``v-hide`` directive that applies opacity instead of ``display: none``.
* Scope styles of PlayerManager
* Share more global classes
=> refactor: v-hide directive and minor cleanup

client/components/Buttons/CastButton.vue, client/components/Buttons/PlaybackSettingsButton.vue, client/components/Buttons/SubtitleSelectionButton.vue, client/plugins/supportedFeaturesPlugin.ts, client/store/deviceProfile.ts, package.json
=> Fix Cast button margins and linter warnings

client/assets/global.scss, client/components/Layout/AudioControls.vue, client/components/Layout/VolumeSlider.vue
Just a few small things a chaned in my local branch that might be useful to merge.
=> refactor(css): add some context to a few hacks and remove duplicated rule

client/components/Buttons/PlaybackSettingsButton.vue, client/components/Players/PlaybackInfoCard.vue, client/components/Players/PlayerManager.vue, client/components/Players/ShakaPlayer.vue, client/locales/en-US.json, client/store/playbackManager.ts, package.json
Adds some playback information for debugging purposes.
=> feat(video-osd): add playback information

client/components/Item/RelatedItems.vue
Fixed up version of #1138, opened due to the detached head borking the PR...
=> fix(relateditems): related items excludes albums from the same artist

src/components/Players/HlsPlayer.vue
fix #1557 
Won't work until jellyfin/jellyfin#6777
=> feat(subs): add styling to subtitles

src/components/Players/HlsPlayer.vue, src/components/Players/ShakaPlayer.vue, src/store/playbackManager.ts
=> feat(playback): keep volume between playback sessions

src/components/Players/HlsPlayer.vue, src/components/Players/PlayerManager.vue, src/plugins/supportedFeaturesPlugin.ts
Signed-off-by: Thibault Nocchi <1619359+ThibaultNocchi@users.noreply.github.com>
=> feat(video): iPhone native fullscreen

package-lock.json, package.json, src/components/Players/PlayerManager.vue, src/nuxt.config.ts, src/plugins/components/clientOnly.ts
I've tested it on FF and Chrome, can someone test on Safari Desktop and Android please?
=> refactor: remove fullscreen dep to do it with native JS method

src/mixins/itemHelper.ts, src/nuxt.config.ts
Turns out this was easier than I expected. Should fix #1683 
I tested a few routes and all of them worked but items, so I fixed their path resolution. I don't know if somewhere else changes are needed. @doc-code-hub Care to pull this branch and test extensively if all your tests pass now?
=> fix(router): 404 on reloads

.docker/nginx.conf, Dockerfile, nginx.conf, src/nuxt.config.ts
Refering to #1683 i've made this simple edit by adding a custom nginx.conf and adding it into the Dockerfile.
I started from the default nginx.conf ([link](https://gist.githubusercontent.com/nishantmodak/d08aae033775cb1a0f8a/raw/ebea0ae66e0a0188009accae2acba88cc646ddcd/nginx.conf.default)) and I modified some parts by adding in particular:
```nginx
location / {
try_files $uri $uri/ $uri.html /index.html;
}
```
This requires no action by users to deploy and solve the problem!
=> fix(nginx): fix 404 when refreshing page with custom nginx.conf

README.md
=> docs: add cf page back

.github/workflows/codeql-analysis.yml, .github/workflows/dependency-review.yml
https://github.blog/2022-04-06-prevent-introduction-known-vulnerabilities-into-your-code/
=> ci: add dependency review action to PR pipelines

.github/workflows/pull_request.yml, .github/workflows/release.yml, .github/workflows/unstable.yml, frontend/components/Players/HlsPlayer.vue, frontend/nuxt.config.ts
The regex for webpack testers was incorrect for Windows.
https://github.com/webpack/webpack/issues/2073
=> fix: Windows build and upload Tauri artifacts

frontend/components/Players/PlayerManager.vue
* force exit browser fullscreen when minimizing player
* force exit browser fullscreen when stopping playback
=> fix: force exit fullscreen when minimizing or stopping player

frontend/components/Buttons/FilterButton.vue
=> Scrollbar now shows in only vertical directions

frontend/components/Players/PlayerManager.vue
**Changes**
Fullscreen can now be toggled on doubleclick.
**Issues**
Closes #1775
=> feat(player): add double click to fullscreen

.github/workflows/automation.yml, .github/workflows/codeQL.yml, .github/workflows/code_quality.yml, .github/workflows/deploy.yml, .github/workflows/unstable.yml
Make our CI populate the same kind of comment that was made by the CFPages app.
=> ci: CFPages comments

frontend/pages/settings/index.vue, frontend/pages/settings/logs-and-activity.vue
**Changes**
Fixed the logs and activity page header translation label to be visible for consistency.
**Issues**
None
=> Fix logs and activity page header

frontend/components/Players/ShakaPlayer.vue
**Changes**
Added a video container to make the video fit it's parent container. It is disabled when the video is shrunk into a smaller view.
**Issues**
Partialy fixes #1773
=> Fix horizontal scrollbar in the video player

.github/workflows/automation.yml, .github/workflows/codeQL.yml, .github/workflows/code_quality.yml, .github/workflows/deploy.yml, .github/workflows/job_messages.yml
* Shorter version of commit sha
* Show normal URL when deploying to master
* Reusable job system workflow
* Add links to workflow runs for easier debugging
* Ignore documentation files on automation workflow
=> ci: final improvement pass

README.md
Added docker command for running Docker Container with prebuilt containers
=> Adding details for running Docker Container

frontend/nuxt.config.ts
add Thai translations to the nuxtjs config.
=> feat(lang): add Thai translation

frontend/src/components/Item/Metadata/MetadataEditor.vue, frontend/src/components/System/SelectedDeviceInfo.vue, frontend/src/composables/index.ts, frontend/src/composables/use-datefns.ts, frontend/src/pages/person/_itemId/index.vue, frontend/src/pages/settings/logs-and-activity.vue, frontend/src/utils/time.ts
Moves all the locale handling of datefns to a function-agnostic composable
=> refactor: datefns composable

frontend/src/components/Item/SeasonTabs.vue
This fixed the SeasonTabs component that shows episodes per season in the `series/_viewid` page.
=> fix: SeasonTabs component

frontend/src/components/Buttons/FilterButton.vue, frontend/src/components/Buttons/PlayButton.vue, frontend/src/components/Buttons/ScrollToTopButton.vue, frontend/src/components/Buttons/SortButton.vue, frontend/src/components/Buttons/TypeButton.vue, frontend/src/components/Forms/AddServerForm.vue, frontend/src/components/Forms/LoginForm.vue, frontend/src/components/Layout/AppBar/AppBar.vue, frontend/src/components/Layout/AudioControls.vue, frontend/src/components/Layout/Carousel/Item/ItemsCarousel.vue, frontend/src/components/Layout/VolumeSlider.vue, frontend/src/components/System/LocaleSwitcher.vue, frontend/src/components/Wizard/WizardAdminAccount.vue, frontend/src/components/Wizard/WizardLanguage.vue, frontend/src/components/Wizard/WizardMetadata.vue, frontend/src/components/Wizard/WizardRemoteAccess.vue, frontend/src/layouts/server.vue, frontend/src/pages/genre/_itemId/index.vue, frontend/src/pages/server/login.vue, frontend/src/pages/server/select.vue, frontend/src/pages/settings/apikeys.vue, frontend/src/pages/settings/devices.vue, frontend/src/plugins/vuetify.ts
Use `variant="text"` by default on buttons to match master style
=> style: switch button to variant text

frontend/src/components/Buttons/PlayButton.vue, frontend/src/components/Item/CollectionTabs.vue, frontend/src/composables/use-i18n.ts, frontend/src/composables/use-remote.ts, frontend/src/composables/use-vuetify.ts, frontend/src/pages/metadata/index.vue, frontend/src/plugins/remote/socket/index.ts, frontend/src/store/items.ts, frontend/src/store/userLibraries.ts, frontend/src/utils/playback-profiles/helpers/codec-profiles.ts, frontend/types/global/plugins.d.ts
Several smaller unrelated commits that I've stacked together.
Let me know if you'd like separate PRs for these, but I figure they're small enough it isn't worth it.
I recommend reviewing the diffs per commit, since they're separated logically in that way.
=> chore: little bit of cleanup

frontend/src/components/Buttons/FilterButton.vue, frontend/src/components/Buttons/SortButton.vue, frontend/src/components/Buttons/TypeButton.vue, frontend/src/components/Item/CollectionTabs.vue, frontend/src/components/Skeletons/SkeletonItemGrid.vue, frontend/src/pages/library/_viewId.vue, frontend/src/utils/__tests__/items.spec.ts, frontend/src/utils/items.ts
Generally works the same as the previous page, with the bonus of having a watching on the viewId parameter for when libraries change.
=> Rewrite library view

frontend/package.json, frontend/src/store/playerElement.ts, frontend/vite.config.ts, package-lock.json
Blocked by:
* ThaUnknown/jassub#19 - font problem on iOS/iPadOS
* ThaUnknown/jassub#20 - see if we can drop the static copy of the .wasm file
=> feat: implement jassub instead of libass

.docker/docker-entrypoint.sh, .docker/nginx.conf, .docker/setup.sh, Dockerfile, frontend/index.html, frontend/src/plugins/router/index.ts, frontend/src/utils/external-config.ts
* Fix some markup validation errors in index.html
* Fix config.json fetching
* Fix incorrect variable name for external config
=> ci: update Dockerfile to adapt it to the new config.json

frontend/src/components/Layout/AppBar/AppBar.vue, frontend/src/components/RouterViewTransition.vue, frontend/src/components/System/LoadingIndicator.vue, frontend/src/composables/index.ts, frontend/src/composables/use-loading.ts, frontend/src/layouts/server.vue, frontend/src/plugins/remote/axios/index.ts
Show a v-progress-linear when an Axios request is happening or suspense is loading content.
In a similar fashion to GitHub's and YouTube loading indicators
=> show linear progress when making network requests

frontend/src/components/Item/Card/Card.vue, frontend/src/plugins/vuetify.ts
=> fix: unplayed chips UI readable and globally rounded chips

frontend/index.html, frontend/src/assets/styles/global.scss, frontend/src/layouts/default.vue
The splashcreen and video/music/login pages with scrollbars were really ugly
=> feat: permanent scrollbars in default layout only

frontend/src/store/userLibraries.ts
* nextUp was called for each library, while the function itself overwrote the whole state. This resulted in nextUp being populated by the latest library fetched. I reduced it to a single call cause removing the parentId gets us the classic nextUp experience from web.
* Wait the refresh promises at the end of the function, as we don't have to wait for them in the body of the function
=> fix: nextup can have undefined parent id

frontend/src/pages/search.vue
* Memoize previous search queries
* Use computed for data filters
* Fix old results temporarily appearing when clearing the query
=> refactor(vue3): search

frontend/src/pages/server/login.vue, frontend/src/plugins/remote/axios/index.ts
=> fix: properly disconnect user when server is unreachable

frontend/src/components/Buttons/Playback/PlayButton.vue, frontend/src/pages/item/_itemId/index.vue, frontend/src/store/playbackManager.ts, frontend/src/utils/forms.ts
fix #1931 
Thanks to @HazilMohamed for catching the issue and implementing the v-select fix :)
=> feat: working video version picker

frontend/src/store/playerElement.ts
Now attached fonts should load and not falling back to Liberation Sans
**Preview**
=> feat: load attached fonts properly

frontend/locales/en-US.json, frontend/src/components/Item/ItemMenu.vue, frontend/src/store/playbackManager.ts, frontend/src/utils/items.ts
Split from the following PR: https://github.com/jellyfin/jellyfin-vue/pull/1951
=> feat: add Instant Mix to context menu

frontend/locales/en-US.json, frontend/src/App.vue, frontend/src/components/Dialogs/ConfirmDialog.vue, frontend/src/components/Item/ItemMenu.vue, frontend/src/components/Playback/TrackList.vue, frontend/src/composables/index.ts, frontend/src/composables/use-confirm-dialog.ts, frontend/src/store/userLibraries.ts, frontend/types/global/components.d.ts
Split from the following PR: #1951
=> feat: add Delete Item to context menu

frontend/src/store/items.ts, frontend/src/store/taskManager.ts
Accompaniment for PR #1963 
For anything other than library, the task indicator would just infinitely run since their changes are published to `LibraryChanged` message.
Although, sometimes it will still run if there's no changes applied to it.
=> fix: scanning task does not finish running

.vscode/extensions.json, frontend/src/components/Buttons/LikeButton.vue, frontend/src/components/Buttons/MarkPlayedButton.vue, frontend/src/components/Buttons/Playback/PlaybackSettingsButton.vue, frontend/src/components/Buttons/SubtitleSelectionButton.vue, frontend/src/components/Item/Card/Card.vue, frontend/src/components/Item/ItemMenu.vue, frontend/src/components/Item/MediaStreamSelector.vue, frontend/src/components/Item/Metadata/ImageSearch.vue, frontend/src/components/Item/Metadata/MetadataEditor.vue, frontend/src/components/Item/Metadata/MetadataEditorDialog.vue, frontend/src/components/Layout/AppBar/AppBarButtonLayout.vue, frontend/src/components/Layout/TimeSlider.vue, frontend/src/components/Layout/VirtualGrid/VirtualGrid.vue, frontend/src/components/Playback/PiPVideoPlayer.vue, frontend/src/components/RouterViewTransition.vue, frontend/src/components/System/Snackbar.vue, frontend/src/pages/person/_itemId/index.vue, frontend/src/pages/playback/video/index.vue, frontend/src/plugins/remote/index.ts, frontend/src/plugins/remote/types.d.ts, frontend/src/store/playbackManager.ts
A collection of refactors that have been long sitting in my local branch.
* Use const for Snackbar state
* Script setup declaration
* Clean up comments
* Only allow a single ItemMenu opened
* Simplify the complex function of playbackManager
=> Minor refactors

frontend/src/components/Forms/AddServerForm.vue, frontend/src/plugins/remote/auth/index.ts
* Improve handling of server connection logic, merging it properly in the auth plugin.
* Move state inside the singleton
Hopefully fixes #1958 and improve #1843
=> fix: server version too low in edge cases

frontend/locales/en-US.json, frontend/src/plugins/remote/auth/index.ts
=> feat: better server version message

frontend/.eslintrc.js, frontend/src/components/Buttons/FilterButton.vue, frontend/src/components/Buttons/Playback/PlaybackSettingsButton.vue, frontend/src/components/Buttons/SortButton.vue, frontend/src/components/Buttons/SubtitleSelectionButton.vue, frontend/src/components/Buttons/TypeButton.vue, frontend/src/components/Forms/LoginForm.vue, frontend/src/components/Item/Identify/IdentifyDialog.vue, frontend/src/components/Item/Identify/IdentifyResults.vue, frontend/src/components/Item/MediaStreamSelector.vue, frontend/src/components/Item/Metadata/DateInput.vue, frontend/src/components/Item/Metadata/ImageSearch.vue, frontend/src/components/Item/Metadata/MetadataEditor.vue, frontend/src/components/Item/Metadata/MetadataEditorDialog.vue, frontend/src/components/Item/Metadata/PersonEditor.vue, frontend/src/components/Item/Metadata/RefreshMetadataDialog.vue, frontend/src/components/Layout/Carousel/Carousel.vue, frontend/src/components/Layout/Carousel/CarouselProgressBar.vue, frontend/src/components/Layout/Images/Blurhash/BlurhashCanvas.vue, frontend/src/components/Layout/VirtualGrid/VirtualGrid.vue, frontend/src/components/Playback/UpNext.vue, frontend/src/components/RouterViewTransition.vue, frontend/src/components/System/AddApiKey.vue, frontend/src/components/Users/UserCard.vue, frontend/src/components/Wizard/WizardAdminAccount.vue, frontend/src/components/Wizard/WizardLanguage.vue, frontend/src/components/Wizard/WizardMetadata.vue, frontend/src/components/Wizard/WizardRemoteAccess.vue, frontend/src/store/playerElement.ts, frontend/vite.config.ts
Blocked by https://github.com/vuejs/vue-eslint-parser/issues/200
Fixes most code smells on SonarCloud.
=> refactor: use Vue 3.3 new features

frontend/package.json, frontend/src/components/Item/Identify/IdentifyDialog.vue, frontend/src/store/clientSettings.ts, frontend/src/store/items.ts, frontend/src/store/playbackManager.ts, frontend/src/store/playerElement.ts, frontend/src/store/taskManager.ts, frontend/src/store/userLibraries.ts, package-lock.json
klona is miles faster and it's the most popular object cloning library: https://www.npmjs.com/package/klona
=> perf: replace lodash's cloneDeep with klona

README.md
- Finish contributing port to the wiki
- Add warning for users, so they access the Hosted Instance using HTTPS
- Put the privacy disclaimer under a summary
=> docs: minor chores

.devcontainer/devcontainer.json, .devcontainer/postunpack.sh, .github/workflows/quality_checks.yml, .github/workflows/release.yml, .github/workflows/unstable.yml, packaging/tauri/README.md, packaging/tauri/apt_packages, packaging/tauri/package.json
* Uniformize commands with frontend
* Install missing dependencies for building in devcontainer
* Improve CI dependency fetching for building Tauri
=> chore: improve tauri packaging

frontend/src/components/Item/ItemGrid.vue, frontend/src/components/Layout/VirtualGrid/VirtualGrid.vue
Unnecessary due to the performance improvements introduced in Vue 3.4
=> perf: remove throttling from virtual grid

frontend/src/components/Layout/Carousel/Carousel.vue, frontend/src/components/Layout/Carousel/CarouselProgressBar.vue, frontend/src/components/Layout/SwiperSection.vue, frontend/src/pages/playback/music.vue
Minor cleanup of swiper's code
There is an issue in swiper (https://github.com/nolimits4web/swiper/issues/7151) that affects the index calculation and the display of progress bars. Waiting for upstream fix.
=> refactor: swiper

frontend/scripts/paths.ts, frontend/vite.config.ts
Workaround sourced from https://github.com/vitejs/vite/issues/15153
=> fix: windows builds

frontend/index.html
Add mobile web app meta tags in index.html.
=> Add web app tags

packaging/docker/contents/setup.sh
=> fix(docker): `allowServerSelection` was not being parsed correctly

frontend/src/store/playbackManager.ts
=> refactor: playback reporting throttling

packaging/docker/Dockerfile, packaging/docker/contents/postunpack.sh
=> fix(packaging): rootless Docker not working in some systems

frontend/src/plugins/remote/auth/index.ts, frontend/src/plugins/remote/axios/index.ts, frontend/src/store/index.ts, frontend/src/utils/data-manipulation.ts
=> fix: defaults merging, verify token is really deauthed

frontend/src/components/Layout/AppBar/AppBar.vue, frontend/src/components/Layout/Navigation/NavigationDrawer.vue, frontend/src/pages/index.vue, frontend/src/plugins/router/index.ts, frontend/src/plugins/router/middlewares/meta.ts, frontend/src/utils/data-manipulation.ts
This fixes the backdrop being persisted incorrectly across routes
=> fix: wrong defaulting of meta

frontend/src/store/playback-manager.ts
Due to throttling, status events were being skipped.
Fixes #2285
=> fix(playback): playback reporting

frontend/package.json, frontend/src/assets/styles/global.css, frontend/src/components/Layout/AudioControls.vue, frontend/src/components/Layout/SwiperSection.vue, frontend/src/main.ts, frontend/src/pages/artist/[itemId].vue, frontend/src/pages/item/[itemId].vue, frontend/src/pages/musicalbum/[itemId].vue, frontend/src/pages/person/[itemId].vue, frontend/src/pages/series/[itemId].vue, package-lock.json
This font has been suggested by Erik (our UI/UX epert) in Matrix ([link](https://matrix.to/#/!kPTHLknOmRaexLxUwT:matrix.org/$Zi4guWvNG8SsXZuhxnBYAmu2CRrqvQ6sSvTMGsdxfmw?via=bonifacelabs.ca&via=t2bot.io&via=matrix.org)).
=> feat(ui): replace inter with figtree

frontend/src/components/Buttons/QueueButton.vue, frontend/src/components/Item/MediaInfo.vue, frontend/src/components/Playback/UpNext.vue, frontend/src/pages/playback/video.vue, frontend/src/store/playback-manager.ts, frontend/src/utils/time.ts
=> fix(time): ends at not taking current time into account

frontend/src/composables/apis.ts, frontend/src/plugins/router/middlewares/login.ts, frontend/src/store/api.ts, frontend/src/utils/items.ts
* This caused swiper progress bar to not be shown correctly
* The issue was that latestFromLibrary was called inside the array, not passed as a promise.
=> fix: rerendering in home page

frontend/eslint.config.js, frontend/src/components/Layout/Backdrop.vue, frontend/src/components/Layout/Carousel/Item/ItemsCarousel.vue, frontend/src/components/Playback/UpNext.vue, frontend/src/composables/backdrop.ts, frontend/src/composables/page-title.ts, frontend/src/pages/artist/[itemId].vue, frontend/src/pages/genre/[itemId].vue, frontend/src/pages/index.vue, frontend/src/pages/item/[itemId].vue, frontend/src/pages/library/[itemId].vue, frontend/src/pages/musicalbum/[itemId].vue, frontend/src/pages/person/[itemId].vue, frontend/src/pages/playback/music.vue, frontend/src/pages/series/[itemId].vue, frontend/src/pages/server/add.vue, frontend/src/pages/server/login.vue, frontend/src/pages/server/select.vue, frontend/src/pages/settings/index.vue, frontend/src/pages/settings/logs-and-activity.vue, frontend/src/plugins/router/index.ts, frontend/src/plugins/router/middlewares/meta.ts, frontend/src/utils/images.ts, frontend/types/global/plugins.d.ts, frontend/types/global/util.d.ts
Definitely fixes all the race conditions that lead to missing backdrop/persistent backdrop in places where it shouldn't be.
=> refactor: backdrop and page title as composables

frontend/src/assets/styles/index.css, frontend/src/main.ts
Cherrypicked from my ongoing work in the [data-fetching](https://github.com/jellyfin/jellyfin-vue/tree/data-fetching) branch, which aims to finish the work that #2201 started and improve even more the resiliency of the application load.
This specific commit was cherry-picked for #2360, since that PR needed to ensure that all the font resources are loaded.
=> feat: ensure all resources are loaded before mount

frontend/src/components/Layout/SettingsPage.vue, frontend/src/composables/page-title.ts, frontend/src/pages/settings/logs-and-activity.vue, frontend/src/pages/settings/users/new.vue
Avoid having to set the page title in every setting page
=> refactor: simplify page titles in setting pages

.github/workflows/__quality_checks.yml
Also issue `analyze` command in CI to have reports of cycles
=> ci: use matrix strategy for common commands

frontend/src/assets/styles/splashscreen.css, frontend/src/components/Item/Card/GenericItemCard.vue, frontend/src/components/Layout/AppBar/AppBar.vue, frontend/src/components/Layout/Backdrop.vue, frontend/src/components/Layout/Navigation/NavigationDrawer.vue, frontend/src/components/lib/JApp.vue, frontend/src/components/lib/JTransition.vue, frontend/src/composables/backdrop.ts, frontend/src/pages/playback/video.vue, frontend/src/splashscreen.ts, frontend/src/store/index.ts, frontend/types/global/util.d.ts, frontend/uno.config.ts
Also refactored styles to use UnoCSS and fixed some type issues
=> feat(a11y): add no transparency setting detection

frontend/src/plugins/remote/socket.ts
This is the initial work for better progress reporting when scanning and in dashboard.
Doing it now so I don't forget how it should be done later.
=> feat(socket): subscribe to all events

frontend/src/components/lib/JTransition.vue
Inspired by @brys0 on [Matrix](https://matrix.to/#/!kPTHLknOmRaexLxUwT:matrix.org/$-2SSyUrRxqdYH-5C5-37bGE2XzlEZCCVUH5WY3AxlrM?via=bonifacelabs.ca&via=t2bot.io&via=matrix.org)
Reproduction of this feature on [SFC Playground](https://play.vuejs.org/#__PROD__eNqdVuFu2zYQfpWrFiROYElxkwyB5qTYmmJogS1Bmx8bYGClpZPNVBIFknKcZn73HilZph3LdQsEMXl3vPvu7jtSz97vZRnMKvQib6hiyUsNCnVVXo8KnpdCangGiSksIJUihyMyPfqt1X24l6xQXHNRNPogdGTGsbEehrVrckobjXmZMY20Axg65lZAooTPmiVtyuthaNDYTbhSDVXJ2hNhuxm68UkyDJ1wXt/TKhZFyifBgxIFJf1sDo28WOQlz1DeluacGnkRWI3RsSwTjx+sTMsK+0t5PMX4yxb5g5ob2ci7k6hQznDktTrN5AR1rX736W+c07pV5iKpMrLeofyISmSVwVib/VEVCcF27Cza97Y9vJjcq3dzjVSOJikD1FgurP3Iowa93ZH6Cu5ZcG7PjYoFVXGjx4Y8610tr99OeZZILMjbMxyoTGgVJJiyKtO94yDDYqKnsFgsmzs0HRAFFrqOHXF1NfImUlQlvIFVuD+tJHIkI68+EWdMmTMPvn6hm/ljXiSkPGBaS8qxCVKwHEmacMX …
=> feat(JTransition): safeguard for fragment nodes

frontend/src/composables/apis.ts, frontend/src/composables/backdrop.ts, frontend/src/store/client-settings/index.ts, frontend/src/store/super/common-store.ts, frontend/src/store/super/synced-store.ts, frontend/src/utils/validation.ts, frontend/types/global/util.d.ts, package-lock.json, package.json
Some other types coulc probably be refactored, but this is a good start and these others can be tackled later.
=> refactor: use type-fest types

frontend/src/store/player-element.ts, frontend/types/global/attributes.d.ts
Minor type fix for ASSUB as well
=> feat(types): add types for v-hide directive

frontend/src/store/index.ts, packages/vite-plugins/index.ts, packages/vite-plugins/tsconfig.json
Make Vite serve the report itself using the preview server
=> fix: sonda on codespaces

frontend/src/components/Item/SeasonTabs.vue, frontend/src/components/Layout/Artist/ArtistTab.vue, frontend/src/components/Playback/TrackList.vue, frontend/src/pages/artist/[itemId].vue, frontend/src/pages/genre/[itemId].vue, frontend/src/pages/item/[itemId].vue, frontend/src/pages/musicalbum/[itemId].vue, frontend/src/pages/person/[itemId].vue, frontend/src/pages/search.vue, frontend/src/pages/series/[itemId].vue
Supersedes #2531, but applying it to all components
=> refactor: use parallel fetching when possible
