jellyfin/jellyfin-vue

- nuxt.config.ts
- package.json
- yarn.lock
icons are bundled in the web client to avoid needing internet connection to retrieve them
> feat: offline availability of icons pack

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .gitattributes
Adds a [devcontainer config](https://code.visualstudio.com/docs/remote/create-dev-container) for vscode with the following setup:
* node v12
* yarn
* typescript
* eslint
* exposes port 3000
* `yarn install`  is run on startup
* zsh as default shell (include oh-my-zsh and completions)
* zsh history preservation between runs
* vscode extensions:
* dbaeumer.vscode-eslint
* octref.vetur
* esbenp.prettier-vscode
I additionally added `.gitattributes` to fix line-ending problems when running the devcontainer on Windows ([ref](https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-containers-resulting-in-many-modified-files)).
> feat(dev): add vscode devcontainer config

- components/LoginForm.vue
- components/UserButton.vue
While waiting for the API to be in a working state, this adds support for showing the user's picture if they have one.
Otherwise it will show the fallback icon, like before
> feat(userbutton): add profile picture support

- nuxt.config.ts
setting host to 0.0.0.0 when launching yarn dev allows devices on LAN to access the dev server
(easier to quickly test something on a phone for instance)
> build(package.json): set host for yarn dev cmd

- components/LoginForm.vue
- components/Snackbar.vue
- layouts/default.vue
- layouts/fullpage.vue
- nuxt.config.ts
- plugins/snackbar.ts
- store/snackbar.ts
This global snackbar can be called in Vue instances, stores and Nuxt contexts.
The method signature is $snackbar(message: string, color: string|undefined|null) and it will appear. If no color is specified, an empty string is given to the Vuetify component and it applies the default of the theme (black for our dark theme).
Closes #18
> Global snackbar

- components/LoginForm.vue
- components/UserButton.vue
- nuxt.config.ts
- package.json
- plugins/user.ts
- plugins/userApi.ts
- plugins/userInit.ts
- store/user.ts
- yarn.lock
Nuxt Auth expects a normal API to poll the user data on refresh, like `/user/me`.
Due to Jellyfin needing the user's ID to fetch their information, this commit registers a new Auth plugin and a persistent Vuex store, saved to localStorage, to perform the request manually when Nuxt starts up.
It then sets all the required information before the client properly starts, meaning the information
is always fresh when the user refreshes the page.
> fix(auth): fix user data disappearing on refresh

- layouts/default.vue
- layouts/fullpage.vue
- pages/login.vue
In nuxt.config.ts, the option 'components' is set to true. Nuxt auto imports used components in templates from the components/ directory.
> refactor: removed component imports

- pages/login.vue
Those props aren't described in the Vuetify API.
* `no-gutters`: doesn't exist on `v-col` and didn't change the styling. Removed.
* `justify`, `align`: also don't exist, even though at least one of them worked. Replaced by a class `text-center` on the title to get the same styling.
> Removed and replaced unexisting props from LoginForm.vue

- components/Card.vue
- pages/library/_viewId.vue
Moves `:to` from `card` to `v-card` in `components/card` since only `v-card` supports `:to`
> fix(library view cards): Fix going from library to item details

- .vscode/settings.json
- components/LocaleSwitcher.vue
- components/LoginForm.vue
- components/UserButton.vue
- layouts/default.vue
- locales/en-US.json
- locales/fr-FR.json
- nuxt.config.ts
- package.json
- pages/item/_itemId.vue
- pages/library/_viewId.vue
- pages/login.vue
- tsconfig.json
- yarn.lock
* Add support for translation through vue-i18n/nuxt-i18n.
* Translate the existing messages into both English and French.
* Add a language switcher for quick switching (Probably temporary, but it helps for now)
* Add i18n-ally settings to VSCode workspace
> feat(i18n): add i18n support 

- components/HomeSection.vue
- nuxt.config.ts
- package.json
- pages/index.vue
- pages/library/_viewId.vue
- plugins/displayPreferenceApi.ts
- plugins/imageApi.ts
- plugins/itemsApi.ts
- plugins/tvShowsApi.ts
- plugins/user.ts
- plugins/userApi.ts
- plugins/userLibraryApi.ts
- plugins/userViewsApi.ts
- store/user.ts
- yarn.lock
Adds support for the following home sections:
* resume
* resumeaudio
* nextup
* latest
Some current sections have been omitted voluntarily for now:
* librarytiles
Makes sense later on, but not a priority
* librarybuttons
Would be implemented with librarytiles and rely on the same component
* activerecordings
Not a priority, annoying to test
* onnow/livetv
Needs a visual redesign, since we don't want the buttons there, only programs
> feat(index): add home sections 

- layouts/default.vue
* Removing one of the dividers in the nav drawer when no library is in the list, to avoid having two dividers displayed
* Hidden the button which enabled / disabled the mini variant of navigation drawer. All the code is still there, only the button is commented in HTML
* Hiding the drawer by default, better for mobile usage in order to avoid having to close it almost every time
* Removed the flex usage in the _viewId page. We should use rows and cols to make a responsive grid.
* Removed the .card and .cardImage classes. First one statically applied a size to the cards, which at least shouldn't be set to the component. Second one didn't have a definition anywhere else.
Feel free to comment on anything. :)
> Design improvements

- components/LocaleSwitcher.vue
- layouts/default.vue
…locale
When switching locale, a reload of the page is triggered. Also, the current active locale is
higlighted in the switcher.
Edit: I see that for instance if I put the locale switcher on the login form, it works without reloading. I don't know why on the home page it doesn't work, I'll look into it.
Edit 2: it now works with computed values for the drawer. This PR is now:
* Computed localizations for the nav drawer
* Removed a getter in locale-switcher
> Localizations fix on nav drawer

- components/Card.vue
Prop 'shape' is specified to be a string, but default value is false. Seeing how the check for existence is an `if(shape)`, putting the default to an empty string doesn't change the result but stops the error in the JS console.
> fix(card.vue): fixed type error of 'shape' prop

- nuxt.config.ts
- plugins/browserDetection.ts
Adds a plugin that injects a class instance into the context with utilities to detect the current platform.
Supports:
* Firefox
* Chrome
* Edge
* Safari
* WebOS
* Tizen
Has utilities for:
* Getting the Safari version
* Guessing if we're on mobile
* Guessing if we're on a Smart TV
Part of #60
> feat(browser): add browser detection plugin

- pages/item/_itemId/index.vue
Makes all content on the item backdrop have a white font color to improve contrast when using light
mode
> fix(item details): fix Incorrect font color when in light mode

- nuxt.config.ts
- plugins/browserDetection.ts
- plugins/playbackProfile.ts
- utils/audioFormats.ts
- utils/codecProfiles.ts
- utils/hlsFormats.ts
- utils/mp4AudioFormats.ts
- utils/mp4VideoFormats.ts
- utils/transcodingFormats.ts
- utils/vpxVideoFormats.ts
- utils/webmAudioFormats.ts
Adds full playback profile generation. Should be identical to jf-web in the result, with some exceptions for dropped platforms.
Part of #60
> Add playback profile detection

- components/Card.vue
- nuxt.config.ts
- package.json
- plugins/browserDetection.ts
- plugins/deviceProfile.ts
- plugins/displayPreferenceApi.ts
- plugins/imageApi.ts
- plugins/itemsApi.ts
- plugins/playbackProfile.ts
- plugins/snackbar.ts
- plugins/tvShowsApi.ts
- plugins/user.ts
- plugins/userApi.ts
- plugins/userInit.ts
- plugins/userLibraryApi.ts
- plugins/userViewsApi.ts
- types/utils.ts
- yarn.lock
* Use core-js 3 for polyfills (Nuxt uses 2 by default)
* Fix the card component trying to get images even if there are none, leading to a bunch of 404s and useless requests
* Fix #92 (Changes the way plugin functions are defined to use type inference for parameters and return values)
* Builds and uses a modern bundle in addition to the "old browser" compatibility one. Still needs a bunch of work in regards to defining targets and such, but it's a start.
> Fix a bunch of things

- components/Card.vue
- components/HomeSection.vue
- layouts/default.vue
- nuxt.config.ts
- pages/index.vue
- pages/library/_viewId.vue
- pages/login.vue
- plugins/page.ts
- plugins/user.ts
- store/page.ts
* Add a Vuex store and the accompanying plugin to set the page title from anywhere.
* Add a back button (hidden when on the home page)
* Fix an issue with some home sections merging incorrectly with others
* Add progress indicator on cards
* Add unplayed count on cards
* Add watched indicator on cards
* Use Jellyfin's grey on the app bar in dark mode (#202020)
> A few more improvements

- components/Card.vue
- components/HomeSection.vue
- components/SeasonTabs.vue
- layouts/default.vue
- mixins/imageHelper.ts
- package.json
- pages/index.vue
- pages/item/_itemId/index.vue
- pages/library/_viewId.vue
- yarn.lock
* Set the number of cards per home section depending on the shape (Thumb or other)
* Cleanup the default layout a bit by moving containers into the views
* Use CSS Grids to display cards in the library browser (Fully responsive, mimics the amount of cards used by home sections)
* Request images with the size of the card instead of the full image size
> Various design improvements

- components/BlurhashCanvas.vue
- components/BlurhashImage.vue
- components/Card.vue
- package.json
- pages/item/_itemId/index.vue
- yarn.lock
Adds two new components:
* BlurhashCanvas - Renders a hash to a canvas with a set size
* BlurhashImage - Takes an item and renders the BlurhashCanvas and a v-img
> feat(card): add blurhash images

- components/Backdrop.vue
- layouts/default.vue
- layouts/fullpage.vue
- nuxt.config.ts
- pages/item/_itemId/index.vue
- store/backdrop.ts
A component has been added to the default layout, which displays an image from a Vuex store.
The Vuex store can either set or clear backdrops.
To set a backdrop, you must pass a BaseItemDto[] in order to retrieve the relevant images. It is designed to allow a rotation of the array, in order to change which backdrop is displayed.
**Note: It's currently only displayed on the item details page. It looks kind of bad, so we might want to redesign the page a bit to make use of the backdrops.**
> feat(backdrop): add backdrop support

- components/BlurhashCanvas.vue
- components/BlurhashImage.vue
- components/Card.vue
- nuxt.config.ts
- package.json
- pages/library/_viewId.vue
- plugins/components/vueVirtualScroller.ts
- yarn.lock
* Adds a responsive virtual scroller to the library pages
* Fixes performance issues with the card component
To get around the limitations of the virtual scroller not supporting grids, we use lodash's `chunk` function to transform the items array with chunks of items (the length of which depends on the breakpoint we're at).
This essentially gives us a bunch of rows of items to pass to the virtual scroll, simulating a grid.
The current implementation of BlurhashImage was somewhat slow in this scenario, so I switched the library to use `blurhash-wasm`, which is a Web Assembly decoder in Rust (@sparky8251 will be happy :smile: ).  
Further performance issues lead to a profiling of the view and I discovered that `v-img` is quite slow in this scenario. I replaced it with `img`, since we're not …
> Add virtual scroller to library view

- components/SkeletonCard.vue
- pages/library/_viewId.vue
Slightly redesigns the empty library placeholder to look nicer.
> feat(library): add card skeletons to the empty library placeholder

- layouts/default.vue
- plugins/browserDetection.ts
- plugins/imageApi.ts
- plugins/itemsApi.ts
- plugins/libraryApi.ts
- plugins/playbackProfile.ts
- plugins/tvShowsApi.ts
- plugins/userApi.ts
- plugins/userLibraryApi.ts
- plugins/userViewsApi.ts
- store/userViews.ts
* Moves the API call for user views into a store
* Adds a getter for navigation drawer items
* Fixes most plugins not being exposed to Vuex
* Changes the default page template to use the Vuex store as a data source instead of the straight API call
> Refactor user views to use a Vuex store

- .docker/mime.types
- .docker/nginx.conf
- Dockerfile
This PR fixes/changes the following:
* Switch from `yarn generate` to `yarn build` to build proper SPA
* add more MIME types potentially used by jellyfin to nginx config
* enable gzip compression in nginx for selected MIME types
* fix routing in nginx
> Dockerfile: fix SPA build, add compression, mime types and routing

- .ci/azure-pipelines-build.yml
What this PR should accomplish:
* Build unstable image after every commit to master
* Build stable image whenever we have a versioned git tag
* Images are built for amd64, armhf and arm64 architectures
* Push images to `jellyfin/jellyfin-vue` on docker hub
It's my first time doing azure ci (code originates from the jellyfin server ci configs with some changes by me) so this may not work as intended - comments are welcome.
An optimized approach could be to create the static files in their own job and not within the Dockerfile and to just copy them over into the different base images in the Dockerfile, but this would prevent users from easily building the image by building the Dockerfile.
> feat(ci): add docker image pipeline

- .ci/azure-pipelines-build.yml
- .ci/azure-pipelines-lint.yml
- .ci/azure-pipelines-test.yml
- .ci/azure-pipelines.yml
- .dockerignore
- Dockerfile
- Dockerfile.dev
This changes should accomplish the following while CI builds (un)stable images:
* additionally push a manifest referring the latest builds:
* `jellyfin/jellyfin-vue:unstable` should be multi-arch and always reference the latest unstable images
* `jellyfin/jellyfin-vue:<version>` should be multi-arch and always reference the corresponding versioned images
Comments are welcome, I have no idea if this works as intended since I can't test it locally.
Based upon [this](https://gist.github.com/awesomebytes/16d0a5fcc4f368a43ac21e5cf3000034) and [this](https://github.com/vslepakov/iot-edge/blob/master/MultiArch/azure-pipelines.yml).
> Add docker manifests to CI to support multi-arch image tags

- .ci/azure-pipelines-build.yml
Seems like the CI loses docker context between tasks and the wrong builder was used (even though the new one was set as default). Changes should make sure that the correct builder is used.
I'm not sure if this works since the PR CI seemed to use the correct driver (images built fine).
> Another attempt on fixing the Docker CI

- nuxt.config.ts
Adds a custom logo and colors to the Nuxt loading screen (Note: These options are somewhat undocumented, currently)
> build(nuxt): add custom logo and colors to nuxt loading screen

- pages/library/_viewId.vue
Since there is a `skeleton-card` displaying empty place holders while the data is being loaded, removing the `0` item count is less confusing.
It will be shown once the loading is complete - and show `0` only when needed.
> fix(_viewid): do not show item count while loading items

- assets/global.scss
Makes scroll bar color more visible
Before:
After:
> fix(scroll bar): fix scroll bar color

- components/SkeletonCard.vue
- components/SkeletonItemGrid.vue
- pages/library/_viewId.vue
**Changes**
- Moves skeleton card grids to a new component `SkeletonItemGrid`
- Changes skeleton card shape based on item type
- Removes `console.error` from `library/_viewId.vue`
> Skeleton Card Sizes

- components/RelatedItems.vue
Hide related items, when finished loading but no related items are found. Previously, the skeleton
loader would continue to show even when no data was returned from the server
> fix(relateditems): hide related items when relevant

- components/BlurhashImage.vue
In cases where there is both a primary image tag, and blurhash primary image tags, but the tags are not
equal, it will throw errors.
To fix this, I have introduced a check to identify if there is a blurhash with that primary image tag
> fix(blurhash): fix blurhash throwing errors

- store/user.ts
Server url is now stored in the server store, it is no longer required to be stored in the user
store\
> refactor(user store): remove serverUrl from user store

- components/AddServerForm.vue
- components/LoginForm.vue
- locales/en-US.json
- nuxt.config.ts
- package.json
- plugins/components/veeValidate.ts
- plugins/veeValidate.ts
- yarn.lock
Initial support for vee-validate.
Validation messages have their translations in the `validation` object in the locales files.
A user suggested that the following was too repetitive (Form fields had their translations in the `fields` object. )
So I removed the field name from the translation.
Rules must be imported in `plugin/veeValidate.ts` or customized in the script section.
Import ValidationObserver, ValidationProvider component:
```
import { ValidationObserver, ValidationProvider } from 'vee-validate';
export default Vue.extend({
components: {
ValidationObserver,
ValidationProvider
},
...
```
Wrap the form and fields:
```
<validation-observer v-slot="{ invalid }">
<v-form ref="form" :disabled="loading" @submit.prevent="userLogin">
<validation-provider
v-slot="{ errors }" …
```
> feat(validation): support for vee-validate

- components/BlurhashImage.vue
- components/Card.vue
During the initial scan, image loads can fail. Currently, we just show a standard broken image from the browser.
This catches the `error` event of the `ìmg` element used by `blurhash-image` and re-emits it to the parent component, which allows the cards to fallback to icons in case an error happens when loading the image.
> fix(card): properly handle image load failure in cards

- components/SkeletonCard.vue
- components/SkeletonItemGrid.vue
Continues work from #318
Fixes card sizes in libraries that do not have use portrait cards
Also add props validation to `SkeletonCard`
> Fix/skell card sized - Fixes incorrect skeleton card sizes in some libraries

- components/UserButton.vue
- layouts/default.vue
- locales/en-US.json
Reworks the navigation drawer a bit to look nicer and removes the duplicate user icon (Note: The screenshots were taken before adding the translation key for the header).
Edit: Added a chevron next to the user name, to indicate the menu
> refactor(navigation): rework navigation sidebar

- layouts/default.vue
Previously, the keys for TV Shows, Movies, Music... were using `i` as they key, this causes issues if there are multiple `v-for` loops both using `i` as the key. This instead uses the `itemId` for the key
> fix(default layout): fix duplicate keys in default layout

- components/HomeSection.vue
The dash before "Next up", "Libraries" etc. on the index was always dark and wasn't visible on white mode. It now follows the current vuetify theme.
> fix(homesection.vue): fixed dash color not following the white mode

- components/PersonList.vue
Cherry-picked from #275, partially fixed on #362 
This fixes errors on movies where the same person plays more than one role
> fix(personlist): duplicated key

- components/UserButton.vue
Putting the icon in the v-img placeholder makes it appear while the user image is loading (or not at
all) instead of the plain blue circle
Also idk about you, but I got this blue halo around the pic due to the background, I'll try to look into it
> feat(userbutton): image size linked to icon size + default icon in img placeholder

- pages/login.vue
> feat(login): add login disclaimer

- components/HomeHeader.vue
Since I noticed that the Fanart plugin is now working on 10.7 (probably has been for a while), this fixes some oversights in regards to how logos are handled on the home header (Size, but also actually using them for music...)
> fix(home-header): fix logo display for MusicAlbum items

- components/LoginForm.vue
- locales/en-US.json
- pages/login.vue
- schemes/jellyfinScheme.ts
fix #137
---
It adds a stored boolean value `rememberMe` which is checked at `fetchUser`. If it is false, it engages the logout procedure. If remember me is set, it acts the same as today, you can refresh whenever you want or come back later and it'll be logging you back. If not set, a single page refresh logs you out.
In the `login` method, I have to set twice the rememberMe value around L90. This is due to the fact we call `fetchUser` which checks the remembeMe flag and disconnects you if it is false. So at first I set it to true then after the user is fetched, the real value is set. I'm all ears for better hacks/solutions.
~~The first picture is how I've put the remember me button (put the checkbox element after the password one and added a bottom margin). It needs work about spacing. …
> feat: add remember me login feature

- nuxt.config.ts
- package.json
Sets a bunch of PWA manifest and meta tags settings in Nuxt in order to feel more native on mobile devices.
> Set PWA manifest and meta tags settings

- components/UserButton.vue
- layouts/default.vue
- nuxt.config.ts
- package.json
- plugins/nativeWebsocketPlugin.ts
- schemes/jellyfinScheme.ts
- store/index.ts
- yarn.lock
Adds a websocket connection to the client using vue-native-websocket.
Messages get sent to the root store, in a `socket` object in the state, which contains the socket instances, connection status, message and error status.
Components can then subscribe to these messages and filter them based on type.
An implementation of ForceKeepAlive and KeepAlive is provided in the default layout.
> Add websocket support

- components/HomeHeader.vue
- layouts/default.vue
Does what it says on the tin.
**XS (Galaxy S9/S9+)**
**SM (iPad portrait)**
**MD (iPad landscape**
**LG (720p screen)**
**XL (1080p screen)**
> refactor(home-header): make home header section responsive

- locales/en-US.json
- pages/item/_itemId/index.vue
Adds missing translations for:
`subtitles`
`video`
`audio`
on item details page
> fix(item details): add missing translations

- pages/settings/index.vue
To help with the readability of the page, this groups admin settings into logical groups, in order
to break up the flow of that long list of entries.
> refactor(settings): group settings into sections

- .github/workflows/main.yml
- components/PlayerDialog.vue
- components/PlayerManager.vue
This attempts to fix the scroll issue with the player dialog, by extending `v-dialog` and removing a block of code from the `scrollListener`, which was seemingly preventing scroll events on the overlay from doing anything.
I'm not fully sure this works as intended, so **please test this when reviewing**.
> fix(player-manager): fix scroll when a player is open

- components/PlayerManager.vue
- components/VideoPlayer.vue
- store/playbackManager.ts
Adds a snazzy OSD to the mini player, allowing you to stop playback, move to the big player, pause/unpause and skip tracks.
Also fixes a bunch of bugs in the playback manager in order to get this working.
> feat(player-manager): add mini player OSD

- components/TypeButton.vue
- pages/library/_viewId.vue
With the introduction of the filter button and view modes, folder views such as Photos libraries
were broken. This makes some adjustments in order to restore navigation in these libraries.
> fix(library): fix folder navigation and sorting

- components/SeasonTabs.vue
- store/homeSection.ts
- store/tvShows.ts
**Current Approach**
```
store = {
seasons: BaseItemDTo[],
seasonEpisodes: BaseItemDTo[][]
```
**Updated Approach**
The key used is the item Id for the series
```
store = {
[key: string]: {
seasons: BaseItemDTo[],
seasonEpisodes: BaseItemDTo[][]
}
}
```
This allows for multiple seasons to be stored in the vuex store
> feat(season tabs): refactor tvShows Vuex store to use itemIds

- assets/global.scss
- components/HomeHeader.vue
- components/SwiperProgressBar.vue
* Fix a z-index issue where the progress bars were going over the top bar
* Fix the positioning of the bar in the xs and sm breakpoints
* Add padding to the bar to fit better with the other padding around the page
> refactor(swiper-progress): fix z-index issue, responsive placement and adds padding

- pages/library/_viewId.vue
84add64 introduced an issue where Music libraries were treated as folders, thereby returning no items (Because our API is weird like that).
This changes the conditions a bit to properly handle Photos libraries and actual folders, without breaking other libraries.
> fix(library): handle folders properly

- locales/en-US.json
- mixins/formsHelper.ts
- pages/item/_itemId/index.vue
* Replace empty string by `undefined` string when language is unknown for audio & subs
* Fix audio & subs titles being called by a misnamed property
* Fix `v-select` being directly fed the array of values when it's supposed to get an array of objects as { value } (see the Vuetify API, this object can provide a few more options which we don't  use now). It resulted in the select thinking 'activating' every input once one was selected
* Fix logic error for default audio & sub selection (index by the server starts at 1 it seems, we directly used this number to get from the local array which starts at 0)
* Fix audio `v-select` not appearing when a single track was available due to bad boolean logic
> Improvments on item v-select

- components/Layout/HomeHeader/SwiperProgressBar.vue
After going from home to another page, sometimes, the event listeners for the animation end fired up when the progress elements were already destroyed.
This didn't crash, show or cause any visible error to the end user, but ``TypeErrors`` were appearing in the consoles and we don't want this :)
> fix (swiperprogressbar): remove event listeners on destroy

- components/Layout/HomeHeader/HomeHeaderItems.vue
When clicking on a progress bar in swiper, swiper slides all the slides to the destination slide, making the animation look akward.
Switching to fade effect solves this.
> perf(homeheaderitems): switch to fade effect for faster animations when switching between slides apart

- components/Players/PlayerManager.vue
- components/Players/VideoPlayer.vue
- utils/supportedFeatures.ts
All Icons, excluding:
- Play/Pause
- Prev/Next track
- Minimize / Exit
are not currently hooked up to anything
AirPlay and PiP icons are hidden if it is not supported.
Top Left Buttons: Close Player, mini player, PiP mode
Top Right Buttons: SyncPlay, AirPlay, ChromeCast
Bottom Left: Prev Track, Play/Pause, Next Track
Bottom Right: Captions, Settings, Full Screen
> feat(video osd): Add OSD for video playback

- nuxt.config.ts
- package.json
- plugins/axe.ts
- yarn.lock
In an effort to push us towards taking accessibility more seriously, this adds [vue-axe](https://github.com/vue-a11y/vue-axe) when in development mode.
It will run checks on the current page while it runs and point out areas where we can improve accessibility.
Here is an example of the output:
> chore(a11y): add vue-axe when in dev mode

- components/Forms/AddServerForm.vue
See https://github.com/jellyfin/jellyfin-vue/pull/466#discussion_r550742849
We should have been using async here as the store function is async
> fix(addserverform): add missing async/await

- pages/library/_viewId.vue
For merged libraries, the CollectionType is different. This adds it to the list of valid types for refreshing items.
> fix(library): trigger items refresh for user views

- components/Buttons/FilterButton.vue
- components/Buttons/UserButton.vue
- components/Item/ItemMenu.vue
- components/Item/Metadata/MetadataEditor.vue
- components/Item/RelatedItems.vue
- components/Layout/HomeHeader/HomeHeader.vue
- components/Layout/HomeHeader/HomeHeaderWelcome.vue
- components/Layout/Images/UserImage.vue
- components/Players/AudioPlayer.vue
- components/Players/TrackList.vue
- components/Players/VideoPlayer.vue
- pages/artist/_itemId/index.vue
- pages/genre/_itemId/index.vue
- pages/index.vue
- pages/item/_itemId/index.vue
- pages/library/_viewId.vue
- pages/metadata/index.vue
- pages/person/_itemId/index.vue
- pages/settings/index.vue
- schemes/jellyfinScheme.ts
- store/displayPreferences.ts
- store/homeSection.ts
- store/tvShows.ts
- store/userViews.ts
Sometimes, components updates triggered before the logout process completed successfully, crashing the whole client with errors.
I added a check in the two troublesome components: **HomeHeaderItemsWelcome** and **UserButton**
The first commit solves the issue completely, but in an additional commit (which I can revert if not everyone agrees with it/have other proposals), I added the chain operator to all the calls to ``this.$auth`` (except the scheme ones), so we can forget about chaining issues (stuff relying on it not being undefined will ofc still be in trouble) which can cause some problems that we're not able to reproduce.
I also tried logging out in the middle of requests being resolved (with first commit only) and I had no issues.
> Fix logout

- components/Item/TimeSlider.vue
- components/Layout/AudioControls.vue
- components/Players/PlayerManager.vue
- mixins/__tests__/timeUtils.spec.ts
- mixins/timeUtils.ts
Moves time slider to a separate component
Adds test for formatting time
> Refactor/time - Refactor time slider

- components/Layout/HomeHeader/HomeHeaderItems.vue
Adds a parallax effect to the text, similar to the demoed here: https://swiperjs.com/demos/360-parallax.html
I also enabled A11y support, keyboard interaction and improved the logic for the hack used for looped slides.
> feat(homeheader): add parallax effect to swiper and minor improvements

- components/Item/RelatedItems.vue
- components/Layout/Backdrop.vue
- components/Layout/HomeSection.vue
- components/SwiperSection.vue
- nuxt.config.ts
- package.json
- pages/index.vue
- pages/person/_itemId/index.vue
- plugins/components/vueperSlides.ts
- store/homeSection.ts
- yarn.lock
This removes all instances of Vueper Slides in the code, and replaces all the uses with Swiper. The reasoning is that Swiper is a better library and is officially supported on Vue 3 already.
This also removes some code duplication by creating a `<swiper-section>` component, which is able to take all the options of the various old usages of Vueper and replaces it everywhere. It incorporates the loading skeleton, allows you to override the section title and supports multiple sections on one page (through generating a UUID for each instance, which is then used in the root class of the component in order to differentiate it from other instances of Swiper on the page).
This change also leads to fixing a major issue with the old sliders, which prevented usage on mobile. These new sections use …
> Remove Vueper Slides & replace with Swiper

- components/Layout/Images/BlurhashCanvas.vue
- components/Layout/Images/BlurhashImage.vue
- plugins/workers/blurhash.worker.ts
Cherry-picked from #275
Everything from the original PR is here, but the use of Intersection Observer on places where the virtual scroller is being used (until we find a solution for all the scrolling performance issues)
> feat(images): unload not visible images using Intersection observer

- components/Item/Card.vue
- components/Layout/HomeHeader/HomeHeader.vue
- pages/artist/_itemId/index.vue
- plugins/axe.ts
* Prevent Axe from running manually
This requires you to run it manually in the console, but fixes the console refresh that swallows errors
* Corrects the way parent item IDs are found in the home header, fixing the undefined error in some cases
* Mirror jf-web's sorting for albums on the artist pages
With jellyfin/jellyfin-web#2265, sorting for the albums is done properly. We were already filtering by PremiereDate, but this adds ProductionYear and SortName as fallbacks, to mimic jf-web.
* Use thumb images for thumb-size cards (Except libraries, folders and user views)
Ideally, imageUtils would naturally fallback to the Backdrop if there is no thumb, but that's for after ferfega's refactoring effort.
> More small fixes

- assets/global.scss
- assets/styles/HomeHeader.scss
- assets/variables.scss
- components/Buttons/UserButton.vue
- components/Item/Card.vue
- components/Layout/AudioControls.vue
- components/Layout/Backdrop.vue
- components/Layout/HomeHeader/HomeHeaderItems.vue
- components/Layout/Images/BlurhashImage.vue
- components/System/DarkModeToggle.vue
- components/System/LocaleSwitcher.vue
- layouts/default.vue
- locales/en-US.json
- nuxt.config.ts
- pages/artist/_itemId/index.vue
- pages/item/_itemId/index.vue
- stylelint.config.js
* Sets a bunch of colors for the dark Vuetify theme
* Moves some menus and buttons around, adds tooltips
* Improve readability of the app bar buttons when the bar is transparent, by using floating action buttons
**Updated 2020/01/08**
> feat(dark-theme): add dark theme colors

- components/Layout/SettingsPage.vue
- components/Layout/__tests__/SettingsPage.spec.ts
- jest.config.js
- jest.setup.ts
- pages/settings/logsAndActivity.vue
Creates a general settings page component discussed in #542 
This component contains two v-slot
- One containing the action buttons
- One containing the main page content
This component has one optional prop:
- page title, if this is left undefined, both the heading, and action buttons will be hidden
See Image
Green Section - Page title
Yellow Section - Action buttons (Docs/help...)
Red Section - Main content
> refactor(settings layout): create general settings page layout component

- components/Item/Metadata/ImageSearch.vue
- locales/en-US.json
Previously, if no images were found, nothing would be shown, now it shows an message saying "No images found"
> feat(image search): show error message is no images are found

- components/Layout/HomeHeader/HomeHeaderItems.vue
- pages/playback/index.vue
- store/__tests__/backdrop.spec.ts
- store/backdrop.ts
Adds Tests for: 
- committing 'SET_CURRENT_BACKDROP'
- committing 'CLEAR_CURRENT_BACKDROP'
- dispatching 'setBackdrop'
- dispatching 'clearBackdrop'
- gettter 'getBackdropBlurhash'
> test(backdrop): add test for backdrop store

- mixins/__tests__/formsHelper.spec.ts
- mixins/__tests__/timeUtils.spec.ts
**TImeUtils**
Covers cases where input is `null` or `undefined`
**FormsHelper**
- Adds tests for converting from an array of items, to an array of objects to be used in a v-select
> FormsHelper, TimeUtils - Add test

- store/__tests__/snackbar.spec.ts
- store/snackbar.ts
Adds tests for:
- Committing 'SET_SNACKBAR_MESSAGE'
- Committing 'RESET_MESSAGE'
- dispatching 'pushSnackbarMessage'
- dispatching 'resetMessage'
> test(snackbar): add tests for snackbar store

- components/Item/ItemMenu.vue
- components/Players/TrackList.vue
- pages/item/_itemId/index.vue
> refactor(item-menu): use item menu everywhere instead of placeholders

- components/Item/ItemMenu.vue
- components/Item/PersonList.vue
- components/Layout/SwiperSection.vue
- locales/en-US.json
- pages/artist/_itemId/index.vue
- pages/genre/_itemId/index.vue
- pages/index.vue
- pages/item/_itemId/index.vue
- pages/library/_viewId.vue
- pages/person/_itemId/index.vue
Switches most of the pages' data fetching to use `asyncData`, which will load data before rendering the page.
Some notable exceptions are the items in libraries and genres pages, since currently the server can be quite slow returning them.
https://user-images.githubusercontent.com/19396809/104120888-9b153900-533a-11eb-8475-f4ecfb62d611.mp4
> refactor: use asyncData for populating page data

- nuxt.config.ts
Change the locale name of nb-NO from 'Bokmål' to 'Norsk'
Fixes #559
> fix(norwegian_locale): change the i18n locale.name for nb-NO

- pages/SelectServer.vue
- pages/login.vue
Increases width of selectserver and login forms to prevent locale switcher wrapping onto next line.
https://user-images.githubusercontent.com/18101008/104755345-3438bb00-5752-11eb-8428-54e27ccb9217.mp4
https://user-images.githubusercontent.com/18101008/104755255-1f5c2780-5752-11eb-8a6a-f4f7d09c9695.mp4
Previously this could occur in some situations
> refactor(login flor): improve responsiveness of selectserver and login pages

- pages/library/_viewId.vue
As proposed [in nuxt's docs](https://nuxtjs.org/docs/2.x/features/loading#programmatically-starting-the-loading-bar)
> fix: this.$nuxt.$loading.finish() is not a function

- components/Players/PlayerManager.vue
Missed in #575. Sometimes, if timing is precise after the mutation notification, Id could be undefined (not only null).
> fix: sometimes Id is undefined when stopping playback

- components/Players/VideoPlayer.vue
Fixes the issue where SD videos did not scale to fill the screen
Fixes #569 
Tested on chrome and firefox. Verified that HD still works as well (see screenshot)
**SD**
**HD**
> fix(video-player): video container does not scale

- components/Players/PlayerManager.vue
- package.json
- tsconfig.json
- yarn.lock
This adds the necessary MediaMetadata object to get proper metadata for the audio and video players.
Note: While officially recommended, the typings file for the MediaSession API seems to have a few issues with regards to the MediaMetadata class. Errors have been silenced until we find a fix.
> Add MediaMetadata support

- yarn.lock
this change happened when I did the yarn install command this morning
> chore(yarn.lock): removed old ts version

- components/Buttons/FilterButton.vue
- components/Buttons/SortButton.vue
- components/Buttons/TypeButton.vue
- pages/library/_viewId.vue
That way we avoid popping or bad inputs while content is not loaded.
https://user-images.githubusercontent.com/10274099/105354474-e6f49780-5bf0-11eb-9010-aa4546093b84.mp4
> feat: disable buttons on load or no items and show progress circular in chip while loading

- components/System/LocaleSwitcher.vue
- pages/login.vue
On lower ends of some breakpoints, user cards were too narrow. Also, on really narrow (<500px) screens the buttons and locale picker disappeared on the right.
> fix(login): fix some responsive problems

- components/Item/Card.vue
Maybe this is subjective, but I always recall seeing this kind of progress indicators starting from the bottom.
**Before**:
https://user-images.githubusercontent.com/10274099/105772891-2e698380-5f63-11eb-9b1a-be151f4d099e.mp4
**After**
https://user-images.githubusercontent.com/10274099/105772910-36c1be80-5f63-11eb-9c77-07876416db32.mp4
> fix: rotate 90 degrees progress circular

- components/Item/SeasonTabs.vue
- components/Layout/HomeSection.vue
- components/Players/TrackList.vue
- pages/genre/_itemId/index.vue
- pages/login.vue
- pages/settings/index.vue
- pages/settings/logsAndActivity.vue
Replaces our manual async/await API calls + loading states with Nuxt's built-in `fetch()` hook, which handles all of that for us and is more flexible and standardized than what we were doing before.
> Use fetch() for data fetching in components

- .vscode/extensions.json
That extension is deprecated and has been replaced by ``lokalise.i18n-ally``
> fix: recommended extensions

- components/Item/RelatedItems.vue
- components/Layout/HomeSection.vue
- nuxt.config.ts
- package.json
- pages/person/_itemId/index.vue
- plugins/persistedState.ts
- yarn.lock
This moves the persistence of the `server` Vuex module to use cookies (Via vuex-persistedstate).
https://user-images.githubusercontent.com/19396809/106182473-239b3280-619f-11eb-9f0b-04b21820c61d.mp4
As a result, some errors about the Swipers showed up, so I set these components to be client-only.
> fix(ssr): fix refresh in SSR mode not keeping the server list and current server

- .ci/azure-pipelines-build.yml
- Dockerfile
- Dockerfile.ci
- Dockerfile.static
Node 14 occasionally crashes with 
```
➜ docker logs -f jellyfin-vue
yarn run v1.22.5
$ nuxt-start
ℹ Modern bundles are detected. Modern mode (server) is enabled now.
ℹ Listening on: http://172.18.0.4:80/
<--- Last few GCs --->
[28:0x55951a5f4e20]   187782 ms: Scavenge (reduce) 4088.1 (4103.6) -> 4087.7 (4104.1) MB, 14.0 / 0.0 ms  (average mu = 0.178, current mu = 0.061) allocation failure
[28:0x55951a5f4e20]   190374 ms: Mark-sweep (reduce) 4088.5 (4101.1) -> 4087.7 (4102.3) MB, 2577.2 / 0.4 ms  (average mu = 0.106, current mu = 0.024) allocation failure scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
error Command failed with signal "SIGABRT".
info Visit …
```
> build(node): downgrade to node 12

- pages/artist/_itemId/index.vue
Should fix #637
Jf-web params:
```
SortOrder: Descending
IncludeItemTypes: MusicAlbum
Recursive: true
Fields: AudioInfo,ParentId,PrimaryImageAspectRatio,BasicSyncInfo,AudioInfo,ParentId,PrimaryImageAspectRatio,BasicSyncInfo
Limit: 100
StartIndex: 0
CollapseBoxSetItems: false
AlbumArtistIds: --
SortBy: PremiereDate,ProductionYear,Sortname
```
jf-vue params (old):
```
userId: --
sortOrder: Descending
parentId: --
sortBy: PremiereDate,ProductionYear,SortName
```
jf-vue params (new):
```
userId: --
sortOrder: Descending
albumArtistIds: --
sortBy: PremiereDate,ProductionYear,SortName,
recursive: true,
includeItemTypes: MusicAlbum
```
> fix(artist details page): fix no albums appearing in artist details page

- components/Players/PlayerManager.vue
- plugins/browserDetection.ts
- store/deviceProfile.ts
- utils/playbackProfiles/directPlayProfile.ts
- utils/playbackProfiles/helpers/codecProfiles.ts
- utils/playbackProfiles/helpers/fmp4AudioFormats.ts
- utils/playbackProfiles/helpers/fmp4VideoFormats.ts
- utils/playbackProfiles/helpers/mp4VideoFormats.ts
- utils/playbackProfiles/helpers/transcodingFormats.ts
- utils/playbackProfiles/transcodingProfile.ts
**Changes**
- Fix browser detection for Edge chromium
- Fix fmp4-hls playback on Edge and Safari
- Reduce OSD timeout from 5 seconds to 3 (https://github.com/jellyfin/jellyfin-web/pull/903)
> Fix FMP4-HLS playback on Edge and Safari

- components/Players/PlayerManager.vue
**Before**
**After**
Unfortunately chrome desktop cannot seek through media tracks however it should not be too difficult to add:
```
navigator.mediaSession.setActionHandler('seekto', (time: number) => { 
this.changeCurrentTime(time)
});
> feat(playback): add functions to handle mediasession inputs

- components/Layout/HomeSection.vue
- pages/index.vue
- store/__tests__/userViews.spec.ts
- store/userViews.ts
Currently, when navigating from home -> a different page -> home, the time taken to reload the homepage can be slow.
This is because, in the creation of home sections, we are awaiting for `userView` from the api. By instead using the userViews in store, the speed is greatly impoved.
**To Test**
To test this you must build + run. It cannot be tested in dev mode.
This is because on network failure, it causes the whole page to show an error message.
Navigate from home -> an item -> turn network connectivity to offline -> back to home, the home sections should load immediately, although with some missing images
> refactor(home sections): improve home sections loading speed by caching userviews

- store/__tests__/servers.spec.ts
- store/servers.ts
Adds tests for: 
- committing 'SET_SERVER_USED'
- committing 'ADD_SERVER'
- committing 'REMOVE_SERVER'
- committing 'CLEAR_SERVERS'
- dispatching 'removeServer'
- dispatching 'clearServers'
Using jest, we are unable to test:
- connectServer
- notifyServerVersionIsLow
- notifyServerCantBeFound
- notifyNoServerUsed
> test(server): add tests for server store

- components/Item/Card/Card.vue
- components/Item/ItemMenu.vue
- components/Layout/AudioControls.vue
Don't force dark theme on ItemMenu
This is my first PR against the new jellyfin-vue repository, so please let me know if there's anything I did wrong or anything I could do better in the future. I found the issue while exploring the new interface. It's looking great!
> fix(itemmenu): don't force dark theme

- codecov.yml
Adjusts the Codecov failure threshold from 0% for 10%, so that small changes go through but larger ones need proper tests.
> ci(codecov): add configuration file

- components/Item/SeasonTabs.vue
- store/__tests__/tvShows.spec.ts
- store/tvShows.ts
Potentially fixes #479
After adding the array of episodes of each season. Sort by parentIndexNumber
> fix(tv show tabs): add sorting to vuex store to fix season ordering

- assets/global.scss
- components/Item/Card/Card.vue
- components/Item/PersonList.vue
- components/Item/RelatedItems.vue
- components/Item/SeasonTabs.vue
- components/Layout/AudioControls.vue
- components/Layout/HomeHeader/HomeHeaderItems.vue
- components/Layout/ItemCols.vue
- components/Layout/SwiperSection.vue
- components/Players/TrackList.vue
- locales/en-US.json
- mixins/itemHelper.ts
- pages/artist/_itemId/index.vue
- pages/item/_itemId/index.vue
- pages/musicalbum/_itemId/index.vue
- pages/person/_itemId/index.vue
- pages/series/_itemId/index.vue
* Refactors the way we get URLs for details pages, by querying `vue-router` directly for a name and parameters. This means we're not using straight strings anymore, making future changes easier.
* Splits some of the details page to remove complexity in the templates. We currently have:
* artist
* item (generic one)
* musicalbum
* person
* series
* Creates a two-column layout component for details pages, making it easier to create new ones
* Uses said component on all details pages, to make them responsive
* Makes some small adjustments to improve small device versions of pages
> refactor: rework details page and make responsive

- .eslintrc.js
- components/Layout/Images/BlurhashImage.vue
Cherry picked from #633 
This conflicts with our prettier config and it doesn't make so much sense anyway.
> chore: disable void html elements erroring on self-close

- nuxt.config.ts
Cherrypicked from #633 
Takes the settings of jellyfin-web for the meta-viewport label, which avoids user scaling and covers the full viewport of the device
> feat: cover viewport and avoid scaling in mobile devices

- pages/item/_itemId/index.vue
- pages/musicalbum/_itemId/index.vue
- pages/series/_itemId/index.vue
Absolute prop was removed here:
a3bb45e: feat: implement favorites
> refactor(item menu): remove unused prop 'absolute' from item-menu

- components/Item/Card/Card.vue
- locales/en-US.json
- pages/artist/_itemId/index.vue
- pages/item/_itemId/index.vue
* Better spacing between albums
* Remove the overlay from card
* Translatable tabs
**Spotify**
**Vue before**
**Vue after**
> fix: spacing in artist pages, translation and cards

- assets/global.scss
- components/Buttons/UserButton.vue
- components/Layout/Images/UserImage.vue
- components/Users/UserCard.vue
Fixes UserImage essentially being broken and fairly useless, and refactors UserCard.
UserImage relied *heavily* on `$auth.user`, making it completely useless in a lot of situations (And breaking the client completely if a public user had an avatar set).
The structure of UserCard was also fairly nonsensical, having a `v-avatar` with a `v-image` in it, whose placeholder was another `v-avatar` with a `v-icon` in it...  
This cleans up the structure and reworks the component to look like this:
One remaining issue is that, since Vuetify is limited, there is no way to easily get these to have button-like hover effects while also being tied to Vuetify's styles without essentially rewriting a custom `v-btn`.
> refactor(user-card): fix user-image and refactor user-card

- components/Forms/LoginForm.vue
Console was warning to add the attribute:
https://www.chromium.org/developers/design-documents/create-amazing-password-forms
> fix: add autocomplete attributes

- .github/workflows/project-automation.yml
Created an action that adds all the new Pull Requests to the "Ongoing development" project, so reviewed PRs can be tracked easily.
> chore: add newly opened Pull Requests to 'Ongoing development' project

- .github/workflows/docker.yml
I found that I was wrong while counting the number of characters that github uses for the short hashes 😅.
This changes it from 8 to 7.
> fix: change hash used for tags from 8 characters to 7 to match github

- .github/workflows/Dockerfile.nginx
- .github/workflows/Dockerfile.ssr
- .github/workflows/docker-release.yml
- .github/workflows/docker.yml
Blocked by #767 as it's build on top of it
Pushes Docker images to ghcr.io alongside DockerHub.
Organization-wide changes at jellyfin/jellyfin-metapackages#7
> chore: push docker images to ghcr.io alongside DockerHub

- layouts/default.vue
- store/index.ts
- store/plugins/websocket.ts
This moves the message handling of the Websocket to a Vuex plugin, in order to avoid cluttering components with having to handle socket messages.
After the Items store refactor, most of the other instances of `subscribe()` should be able to move here or be outright removed.
> Move Websocket message handling to a Vuex plugin

- components/Skeletons/SkeletonHomeSection.vue
> fix(skeleton home section): fix missing margin on skeleton home sections heading

- components/Players/AudioPlayer.vue
- components/Players/PlayerManager.vue
- components/Players/VideoPlayer.vue
Unsubscribes the stores of PlaybackManager, AudioPlayer and VideoPlayer, in an attempt to fix the memory leak the client is facing right now. The rest of the components that contain store watchers won't need those as soon as #801 and #764 are done, so I didn't change those.
Although normally the components where I added unsubscribe are not destroyed and recreated (like cards, which are the problematic ones), they are recreated on logout and a relogin, causing the memory leak to appear, which will be a problem for an user that swaps between accounts frequently.
> perf(memory): unsubscribe from mutation watchers on destroy

- nuxt.config.ts
The [nuxt-pwa config](https://pwa.nuxtjs.org/setup/#installation) actually recommends to use `buildModules` when running in SSR, so this sets the module in the proper config array depending on how we're running.
> build(config): use proper module location for nuxt-pwa when running in ssr mode

- .eslintrc.js
- components/Buttons/LikeButton.vue
- components/Item/Card/Card.vue
- components/Item/Metadata/ImageSearch.vue
- components/Item/Metadata/MetadataEditor.vue
- components/Item/Metadata/PersonEditor.vue
- components/Item/RelatedItems.vue
- components/Item/TrackSelector.vue
- components/Players/PlayerDialog.vue
- package.json
- pages/item/_itemId/index.vue
- pages/series/_itemId/index.vue
- pages/wizard.vue
- schemes/jellyfinScheme.ts
- store/displayPreferences.ts
- utils/playbackProfiles/helpers/codecProfiles.ts
- yarn.lock
This aims to reduce our amount of code smells a bit:
* It adds explicit dependencies for modules we import that weren't in our dependencies before (Vue, Vuetify, Vuex, Axe, etc). This gives us a bit more control over which versions we may want, but also makes it clearer that we directly depend on these.
* It adds the `curly` rule to ESLint. This prevents usage of if statements without curly braces. The reasoning behind this is that this syntax, while allowed in JavaScript and TypeScript, can be confusing at a glance. This rule makes blocks more obvious, leading to less potential for mistakes.
> Reduce code smells on Sonarcloud

- .github/dependabot.yml
``package.json`` used in Docker SSR is not updated by any means.
> ci: update ssr dependencies with dependabot

- components/System/Snackbar.vue
Everywhere in the code base, we pass already translated string to the snackbar store and therefore
the snackbar component. But this one tried to translate it, and of course it didn't work. Visually
there wasn't a problem as i18n displays the strings as is when it doesn't find them, but it's a bug
nonetheless.
fix #765
> fix(snackbar): display the string instead of translating it

- components/Forms/LoginForm.vue
- components/Item/ItemGrid.vue
- components/Item/Metadata/MetadataEditor.vue
- components/Players/AudioPlayer.vue
- components/Players/TrackList.vue
- components/Players/VideoPlayer.vue
- mixins/timeUtils.ts
- nuxt.config.ts
- pages/index.vue
- pages/login.vue
- pages/settings/index.vue
- store/__tests__/backdrop.spec.ts
- store/__tests__/deviceProfile.spec.ts
- store/__tests__/page.spec.ts
- store/__tests__/playbackManager.spec.ts
- store/__tests__/servers.spec.ts
- store/__tests__/snackbar.spec.ts
- store/__tests__/tvShows.spec.ts
- store/__tests__/userViews.spec.ts
- store/playbackManager.ts
- utils/playbackUtils.ts
Quick pass for optimizing our bundle size.
We might need to do the same for all the imports of the axios client, however, unless we don't have the sources (https://github.com/jellyfin/jellyfin-meta/issues/10), I can't check if we can prepare it for better treeshaking
> perf(build): optimize build size

- .github/workflows/label.yml
- .github/workflows/merge-conflicts.yml
A few of the actions (labeler and the merge conflicts one) show up as `github-actions` while they should be `jellyfin-bot` for consistency.
> ci: use the jellyfin-bot token for Github Actions

- .dockerignore
The Dockerfile was wrongly removed in #767 .
This makes building the docker images locally unnecessarily long (due to copying node_modules then removing it by running `npm ci`) and copies unnecessary stuff on the CI.
This restores the original file, and cleans it up a bit.
> build(docker): restore dockerignore

- .github/workflows/docker-release.yml
- .github/workflows/docker.yml
- Dockerfile
- README.md
- package.json
For some reason, npm wasn't passing down the standalone flag to nuxt-build. As a result, dependencies weren't bundled anymore, leading to errors when trying to run it.
This adds a dedicated standalone build command to avoid having to pass down flags.
> fix(docker): fix dockerfile not building the SSR version properly

- pages/artist/_itemId/index.vue
- pages/genre/_itemId/index.vue
- pages/item/_itemId/index.vue
- pages/library/_viewId.vue
- pages/musicalbum/_itemId/index.vue
- pages/person/_itemId/index.vue
- pages/series/_itemId/index.vue
- utils/items.ts
Our item IDs are MD5 hashes in v10, so this isn't doing proper UUID checks but a basic MD5 validity
check.
> feat(pages): validate item IDs when navigating to the pages

- pages/item/_itemId/index.vue
Don't display OriginalTitle if Name has same value. fix https://github.com/jellyfin/jellyfin-vue/issues/836
> check if OriginalTitle and Name values are same

- components/Item/Card/Card.vue
Make the artist name in the item subtitle clickable. fix https://github.com/jellyfin/jellyfin-vue/issues/835. 
I'm not sure if this is the most elegant solution though. The display: block is necessary, since the nuxt-link element sets it to inline and it gets shifted ever so slightly down.
> feat(clickable-artist): add link to card-subtitle

- layouts/default.vue
- layouts/fullpage.vue
- pages/index.vue
- store/homeSection.ts
* Adds `keep-alive` prop to the Nuxt root component, in order to keep some pages in memory, which improved the navigation experience.
This should eventually be coupled with using `fetch()` for all the data fetching around the app, and the use of the `activated` hook with a timestamp check, in order to refresh stale data upon navigation after a certain time (likely after 30s).
https://user-images.githubusercontent.com/19396809/111021546-720e3480-83cd-11eb-8464-4d342838da74.mp4
* Move the data fetching logic of the home page to the `fetch()` hook.
> Improve page navigation and refactor home screen

- components/Buttons/LikeButton.vue
- components/Buttons/__tests__/LikeButton.spec.ts
Removes the red color used on the like button when an item is added.
Using two indicator for the state of the icon is superfluous (Color + filled/outlined) and the red clashes with the rest of the colors on the page. It was also not customizable, since it used the red class from Vuetify.
Now the button only has an outlined or filled icon.
> refactor(like-button): remove color on the like button

- .github/stale.yml
Adds stalebot config to this repository.
The 90 days limit was moved down to 60 days, since 90 days feels way too long for this repository (Deep structural changes happen pretty often still, so 3 months basically means a PR usually has to be rewritten. 
I feel like 60 days feels a bit long too (I'd go with 30), but it's probably a nice middle ground for now.
> ci(stalebot): add stalebot config

- .github/workflows/merge-conflicts.yml
Runs the merge conflict check after a pull request is synchronized with the branch it's currently tracking.
This way, the label is removed after rebases in each PR and not only with commits on master.
> ci: run merge conflict check on PR rebase

- client/assets/variables.scss
The side margins don't look like they were intentional, and it definitely looks better without them. Chromium has a weird white box in the bottom right corner that I didn't bother looking into since Firefox works fine.
> fix(ui): remove side margins from filter panel

- client/locales/en-US.json
- client/pages/musicalbum/_itemId/index.vue
* `Cast & Crew` -> `Cast & crew`
Use a consistent capitalization with the rest of the client
* `By` -> `By {artist}`
Add the artist to the string, to make it more understandable for translators and to allow changing the order of words if the language needs it.
> chore(i18n): reword some translations for consistency and making translations easier

- client/components/Item/RelatedItems.vue
The placeholder for *missing* images doesn't show up but the blurhash looks much better when items are still loading.
> fix(ui): use blurhash image for related items

- client/components/Buttons/QueueButton.vue
- client/components/Players/DraggableQueue.vue
- the hover background was getting cut off on the left side
- all other divider instances only use a single divider so this one looked unusually thick
> fix(ui): span entire queue with hover background and standardize divider size

- client/components/Item/ItemMenu.vue
- client/components/Layout/AudioControls.vue
- item menu button was likely made small for TrackList but doesn't match any other situations with normal sized icons
- album art in AudioControls had no bottom padding and the Name - Artist labels next to it had odd vertical alignment
- explicitly setting elevation to zero will cause a strange border on Firefox and should be avoided
- moved the fullscreen button to the end since this is where most people would expect a fullscreen button
- removed left padding on fullscreen button
> fix(ui): margin and layout changes for audio controls

- .github/workflows/rebase.yml
This has been bothering me for a while. We should use @jellyfin-bot for rebasing instead of @jellyfin.
> ci(rebase): use our bot for rebasing instead of the org

- client/store/playbackManager.ts
The audio player will currently force playback for a different song when the currently playing song is moved to a new location.
> fix(playback): use new queue when setting the current item index

- .github/workflows/rebase.yml
Without the quote yaml interpreter takes it as an incomplete sum instead of a string
> ci(rebase): quote reaction

- client/nuxt.config.ts
- client/plugins/axe.ts
This fixes the persistent warning in dev mode.
Importng as per their docs: https://axe.vue-a11y.com/guide/#nuxt-js
> fix(axe): import axe according to the axe docs to fix warnings

- client/assets/styles/HomeHeader.scss
- client/components/Layout/HomeHeader/HomeHeader.vue
- client/components/Layout/HomeHeader/HomeHeaderItems.vue
- client/components/Layout/HomeHeader/SwiperProgressBar.vue
- client/layouts/default.vue
* Added pagination indicators on hover in the progress bar (desktop only):
Closes #864 
* Hide drawer when entering into the ``mobile`` breakpoint
* Fix margin issues with the swiper.
> Swiper paginators

- client/layouts/default.vue
Fixes #976 (at least it should)
> fix(layout): exclude fullscreen-playback from the pages kept alive

- .eslintignore
- client/components/Item/Card/Card.vue
- client/components/Item/Metadata/ImageEditor.vue
- client/components/Item/PersonList.vue
- client/components/Item/RelatedItems.vue
- client/components/Layout/AudioControls.vue
- client/components/Layout/HomeHeader/HomeHeader.vue
- client/components/Layout/HomeHeader/HomeHeaderItems.vue
- client/components/Layout/Images/BlurhashImage.vue
- client/components/Layout/SwiperSection.vue
- client/components/Players/PlayerManager.vue
- client/components/Players/VideoPlayer.vue
- client/mixins/imageHelper.ts
- client/mixins/itemHelper.ts
- client/pages/artist/_itemId/index.vue
- client/pages/person/_itemId/index.vue
- client/store/tvShows.ts
- client/utils/__tests__/items.spec.ts
- client/utils/items.ts
- client/utils/playbackUtils.ts
Rewrites the utility functions to get image URLs, based on Jellyfin-web.
* Allows for image-type preference and proper fallback (For example, Thumbs will be preferred for thumb-shaped cards, but fallback to backdrops, then primary images)
* Properly handles parent items
* Adds blurhash + fallback for artist and person details page
> imageUtils rewrite

- client/static/robots.txt
As reported by Lighthouse, we don't have a robots.txt:
The one in this disallows all crawling, as a default. It is easily changeable if, for whatever reason, someone wants to make their server public and searchable through Google or something (Though there is no auto-login for a public user at this point in time).
> feat(robots): disallow all crawling

- client/components/Item/Card/Card.vue
The progress bar was positioned next to the image using flexbox.
This changes its positioning to be absolute and aligns it to the bottom of the card, taking the full width and fixing the image size issue that resulted from it taking half of the card space.
Before
After
> fix(card): fix pogress bar position

- .github/workflows/merge-conflicts.yml
I tested the query this action performs in GraphQL explorer and checked the source code and it should fit all our needs. It will label PRs with conflicts only, without paying attention to the rest of the conditions (reviews, rebase, etc).
> chore(ci): replace with actions-label-merge-conflict

- client/pages/library/_viewId.vue
Fixes item listing in mixed libraries.
It was fetching recursively before, when it shouldn't have been.
> fix(library): fixed mixed library item fetching

- .eslintrc.js
- package-lock.json
- package.json
Adds the `no-restrict-globals`, with [confusing-browser-globals](https://www.npmjs.com/package/confusing-browser-globals) to prevent using potentially confusing globals without using `window` first.
The list of provided globals is here: https://github.com/facebook/create-react-app/blob/master/packages/confusing-browser-globals/index.js
> style(eslint): add no-restrict-globals with confusing-browser-globals

- client/pages/series/_itemId/index.vue
#890 -> was only for a film
This not also fixes this Issue on a series.
see https://github.com/jellyfin/jellyfin-vue/issues/836#issuecomment-804008091
> fix(series-item): removed original title if it is the same as the name

- client/components/Layout/AudioControls.vue
Display an empty space at the location of the `UP NEXT` string to prevent the resizing of the toolbar.
#888
> fix(fullscreen-player-next-up): show empty space if it is the last item

- client/components/Layout/SwiperSection.vue
This fixes the client not working on mobile.
A few workarounds were tried, with no avail. Probably have to wait for Vue 3 and the upstream Swiper component for this to be viable.
Edit by ThibaultNocchi: fixes #1058
> Revert swiper arrow hiding/disabling

- client/plugins/itemsPlugin.ts
- client/plugins/userLibraryPlugin.ts
When fetching an array of items for a person/genre/artist, get all the fields of items.
fix #1059
> fix(itemsplugin): fetch all fields of an item when calling getItems

- .github/workflows/docker-release.yml
- .github/workflows/docker.yml
- .github/workflows/label.yml
- .github/workflows/merge-conflicts.yml
- .github/workflows/project-automation.yml
- .github/workflows/rebase.yml
``GH_TOKEN`` seems to be used internally by GitHub and it's making some actions we're using in some repos fail ([Source](https://github.com/alex-page/github-project-automation-plus/issues/39))
*(PRs made from users of the org are always successful, but PRs that aren't don't work, like Dependabot PRs. This can be checked by looking at the history of server repos and Jellyfin Vue)*
The org-wide secret should be renamed to something else to avoid confusion and further replacements or messes in GH's side. This PR replaces ``GH_TOKEN`` with ``JF_BOT_TOKEN``, which should be pretty generic.
> chore: replace GH_TOKEN with JF_BOT_TOKEN

- client/components/Item/SeasonTabs.vue
Also show the the episode title also on mobile devices.
fixes #987
> fix(episode-item): show title and subtile also on mobile devices

- client/nuxt.config.ts
- package.json
We have some chunks in our building output which are roughly 3 MB, which poses a problem for slow connections. Cloudflare Pages is a good example of that: I don't know why, but their servers seems to be extremely slow for serving the pages.
While the chunks are loading, some parts of the pages are not available or incomplete (like the Home and its header or item details), which makes content jump until the specific chunk of that section of the page is fully loaded.
The problem will still exist on single-thread slow HTTP connections, but the situation should be much better on HTTP2 (which is the case of Cloudflare for example and Jellyfin server, once it's able to serve this client) as smaller chunks will be downloaded in parallel.
With this changes, 380 chunks are created as of today, …
> feat: reduce chunk size to speed up slow HTTP/2 connections

- client/components/Layout/AudioControls.vue
Should fix the fullscreen button having an underline since #1025 was merged.
> fix(audiocontrols): re-add span tag on fullscreen button

- client/assets/global.scss
- client/nuxt.config.ts
- package.json
Additionally, added nuxt analyze commands to package.json to ease the bundle analysis later on.
> Load fonts in nuxt.config instead of CSS and treeshake SimpleIcons library

- client/components/Players/ShakaPlayer.vue
We were importing Shaka before setting mux.js as a global. As such, Shaka couldn't find it when
initializing and didn't enable support for transmuxing HLS on non-Apple browsers.
> fix(shaka-player): fix HLS playback

- .github/stale.yml
Adds a few more labels to stalebot, for things that probably shouldn't go stale.
> chore(stalebot): adjust exempt labels

- client/components/Buttons/PlayButton.vue
- client/components/Item/TrackSelector.vue
- client/components/Players/ShakaPlayer.vue
- client/pages/item/_itemId/index.vue
- client/store/playbackManager.ts
Adds pre-playback stream selection.
TrackSelector needs a refactor for this to be a bit cleaner, as I currently have to work around it to fit what Jellyfin expects to get (This PR already has some changes, but it's only workarounds... The whole "clearing" part doesn't work for this, passing it an entire item and a type doesn't work (filtering should be done above), etc.
Supersedes #640
> feat(playback): add track selection to details pages

- client/components/Layout/VolumeSlider.vue
- client/components/Players/ShakaPlayer.vue
- client/store/playbackManager.ts
Hooks up the player's audio output to a Web Audio context, in order to add a GainNode to it.
This allows us to control the gain of the audio, here in order to mimic VLC's "125% audio volume" feature, allowing the user to boost the audio level of their content if it's too low.
**Warning: increasing the gain past 100% can lead to clipping. It's not really an issue, but it's worth knowing.**
> feat(shaka-player): add audio gain support to player

- client/plugins/playbackProfiles/directPlayProfile.ts
- client/plugins/playbackProfiles/helpers/codecProfiles.ts
- client/plugins/playbackProfiles/helpers/fmp4VideoFormats.ts
- client/plugins/playbackProfiles/helpers/tsAudioFormats.ts
- client/plugins/playbackProfiles/subtitleProfile.ts
- client/plugins/playbackProfiles/transcodingProfile.ts
- client/tsconfig.json
- package-lock.json
- package.json
* Adds typings for the Tizen Web APIs
* Simplifies the global video bitrate thing (Remove variables that are just aliases of the global video bitrate)
* Remove some casting (`as`) and properly declare variable types instead
* Use `createProfileCondition` to create profile conditions instead of doing it manually (It's already done in most of the profile creation, but some forward ports from jf-web didn't include them).
* Removed a bit of Tizen code that depends on NativeShell, since we don't support that
* Improved the HEVC profiles comments
* Enabled fMP4 by default for Chrome, Firefox, Safari (Desktop and mobile), Edge, WebOS and Tizen
> Cleanup playback profiles

- .github/workflows/build.yml
- .github/workflows/docker-release.yml
- .github/workflows/docker.yml
- .github/workflows/main.yml
This uses the new cache option for the setup-node action as seen here https://github.com/actions/setup-node#caching-packages-dependencies
It was briefly tested on a fork and it works https://github.com/ThibaultNocchi/jellyfin-vue/actions/runs/1127665027
> ci: use builtin npm cache

- src/components/Item/WatchedIndicator.vue
Declares VChip and VIcon locally, to avoid Vuetify treeshaking them out of WatchedIndicator due to it being functional.
> fix(watched-indicator): fix vuetify component treeshaking

- src/components/Layout/HomeHeader/HomeHeaderAlbumTitle.vue
- src/components/Layout/HomeHeader/HomeHeaderEpisodeTitle.vue
- src/components/Layout/HomeHeader/HomeHeaderGenericTitle.vue
- src/components/Layout/HomeHeader/HomeHeaderItems.vue
- src/mixins/imageHelper.ts
Converts the home header title components to functional components, since reactivity isn't needed there.
> refactor(home-header): use functional components for item titles

- src/assets/variables.scss
- src/nuxt.config.ts
This changes the color scheme to the one used by `next.jellyfin.org`
> style(theme): use new color scheme

- src/components/Players/ShakaPlayer.vue
This provides a more natural input for the volume slider, since the volume will now be exponential instead of linear.
x³ is the same curve used by VLC and MPV, so we're aiming to match familiarity here.
> feat(volume): use a x³ curve for media volume

- src/plugins/directives/hide.ts
From the issue #1365 : The back arrow on the top bar is hidden on the homepage but can be clicked.
So I change the hide directive logic from using CSS opacity to the display property.
> fix(ui): "Soft" back arrow can be clicked when hidden

- package-lock.json
- package.json
- src/nuxt.config.ts
We don't bundle many images as of now and the plugin doesn't seem well maintained, as it's using old versions of imagemin.
We're also heading towards denuxtifying our setup as much as possible so, if in the future we want this, we should use the Vite or webpack standard plugin system.
Fixes #1610
> chore: remove imagemin dep

- .editorconfig
- .prettierignore
- src/assets/loading.html
- src/nuxt.config.ts
Mimics jellyfin-web in that regard (but without the spinner, Nuxt 2's loading templates are really basic and doesn't let us detect the loading state properly to display an spinner when the loading is near to be finished.
https://user-images.githubusercontent.com/10274099/144721396-a1ea196b-ed6d-48ce-9d0c-8ed0ff0de993.mp4
> feat: replace circle loader with Jellyfin-Vue logo

- .github/dependabot.yml
- .npmrc
- package.json
This is an attempt to fix dependabot updates messing with the lockfile version 3.
Right now, npm 8 will generate an v2 lockfile if an user wants to regen their lockfile or issues an ``npm i --package-lock-only``. In order to match this repo's v3, the ``--lockfile-version 3`` argument must be used. This PR adds that config to ``.npmrc`` file, essentially fixing this for everybody transparently, without the need to add any additional CLI arguments.
Also, I bumped the minimum ``npm`` and ``nodejs`` version, as npm ``8.1.0`` had [an issue](https://github.com/npm/cli/pull/3949) where numbers where treated as strings, which was fixed in ``npm 8.1.2`` (which is included in  ``nodejs 16.13.1``)
> Pin lockfile in .npmrc

- README.md
- package.json
- src/nuxt.config.ts
NodeJS GC fails on ARM architectures when running ``fork-ts-checker``. Reverting the change until a better solution is found.
Also fixed an small typo in readme.
> fix(arm): revert #1136 to fix arm builds

- .github/workflows/release.yml
- .github/workflows/unstable.yml
- Dockerfile
After merging #1645, the Docker tags that were pushed and available to registries were the ones that got pushed later, overwriting the other arches.
Disabled parallelization in the workflows that actually push to registries, leaving it only for the ``pull_request`` workflow, where no push happens and where more speedy checks are actually needed.
> chore(ci): fix tags only referencing a single arch

- src/components/Buttons/LikeButton.vue
- src/components/Forms/AddServerForm.vue
- src/components/Item/Card/Card.vue
- src/components/Layout/HomeHeader/HomeHeaderItems.vue
- src/layouts/default.vue
- src/pages/artist/_itemId/index.vue
- src/pages/fullscreen/playback/index.vue
- src/pages/genre/_itemId/index.vue
- src/pages/index.vue
- src/pages/item/_itemId/index.vue
- src/pages/library/_viewId.vue
- src/pages/musicalbum/_itemId/index.vue
- src/pages/person/_itemId/index.vue
- src/pages/series/_itemId/index.vue
- src/pages/server/add.vue
- src/pages/server/login.vue
- src/pages/server/select.vue
- src/pages/settings/index.vue
- src/pages/settings/logsAndActivity.vue
- src/pages/wizard.vue
Keep alive introduces lots of complexities to the state management of the app and it consumes a lot of memory. It's true that removing it introduces some loading time, but what we need is proper item caching instead and we're still not production ready, so this is a minor annoyance.
It never worked properly when switching pages when a promise is running (can be seen easily by going to a library page from the home page while it's loading).
> feat: remove keep-alive

- src/components/Item/ItemMenu.vue
Right clicking components that have the ``item-menu`` component as a child will make the menu appear where the pointer is located
> feat(menu): show context menu when clicking on parent element

- src/assets/global.scss
- src/assets/transitions.scss
- src/components/Buttons/PlayButton.vue
- src/nuxt.config.ts
- src/pages/library/_viewId.vue
Adds an sliding effect while switching pages. Also, removed unused CSS, as Vuetify itself positions the element correctly and it previously had some visual quirks.
> feat(ui): new transitions and CSS fixes for library app bar

- src/components/Buttons/ScrollToTopButton.vue
- src/layouts/default.vue
- src/pages/library/_viewId.vue
- src/store/__tests__/page.spec.ts
- src/store/page.ts
Fixes #1662 
No scrolling animation was added in order to not take a huge performance hit when scrolling larger libraries. Do we want one?
Maybe we can reconsider it when on Vue 3 we use https://github.com/rocwang/vue-virtual-scroll-grid
> feat: scroll to top button in library view

- .github/renovate.json
- Dockerfile
Those dependencies were required for SSR. They are not needed by static (since we went away from imagemin as well).
I also took the opportunity to tidy up the renovate config after the feedback received on https://github.com/renovatebot/renovate/issues/13317
> ci: remove unnecessary deps from Dockerfile and useless config from renovate

- src/components/Forms/AddServerForm.vue
- src/components/Forms/LoginForm.vue
It's annoying the need to go and click the field manually. ith this, we're mimicking all other login forms that do this (i.e Google, Amazon, etc...)
> feat(login): focus forms on login pages automatically

- .github/renovate.json
- .npmrc
Missed to change to the proper manager for Rust while rebasing #1672
> chore: fix npm CI yet again and faulty renovate manager

- frontend/components/Layout/VolumeSlider.vue
- frontend/components/Players/HlsPlayer.vue
- frontend/components/Players/PlayerManager.vue
- frontend/store/playbackManager.ts
Related to #1697:
I **changed** the **keyboard handler** in the player and improved the way listeners are handled.
Added support for the following shortcuts:
_For the full-player_
```
[f] = toggle fullscreen
[Spacebar, k] = play / pause (Spacebar only if there is no focus element, to support Tab)
[Arrowleft, j] =  prev
[Arrowright, l] = next
[m] = mute / unmute
```
_For the mini-player_
```
[f] = toggle back to full-player
```
_Mouse_
Also I added play / pause support by clicking (or touching) on the video player (ignoring the rest of the interface)
> Keyboard and Click player controls for better UX

- frontend/components/Players/HlsPlayer.vue
This patch fixes the regression mentioned in https://github.com/jellyfin/jellyfin-vue/pull/1746#issuecomment-1100641140. On a successful merge/rebase this should be included in https://github.com/jellyfin/jellyfin-vue/pull/1746.
Should this not be the right place to open this PR you are also welcome to close it and cherry pick the changes manually.
> fix(pinia): fix HlsPlayer video playback

- frontend/components/Players/ShakaPlayer.vue
With this patch ShakaPlayer will get a valid playback URL after creation of the player. Closes https://github.com/jellyfin/jellyfin-vue/issues/1754.
As `shakaPlayer` is structured differently as the `HlsPlayer` I'm unsure whether this is actually the right approach to do this and would appreciate some feedback on the way it's done.
> fix(ShakaPlayer): first element in queue won't start playback

- frontend/components/Players/DraggableQueue.vue
- frontend/store/playbackManager.ts
As there hasn't been any activity related to https://github.com/jellyfin/jellyfin-vue/issues/975 for almost a year I'm allowing myself to add a PR to this feature. Closes https://github.com/jellyfin/jellyfin-vue/issues/975.
I am claiming the space from the `itemMenu` which really has no use in the queue panel in order to make space for the button which removes an item from the queue.
Looks like the screenshot above. If there is a specific reason why the `itemMenu` button was there we could also work out another solution for the placement of the `remove` button.
> feat(Queue): items can now be deleted from the queue

- tauri/tauri.conf.json
Fixes Tauri build for Ubuntu.
Windows still fails as the frontend itself can't be built on Windows.
> fix(tauri): remove useBootstrapper option

- .github/workflows/pull_request.yml
- frontend/components/Buttons/PlayButton.vue
- frontend/components/Buttons/QueueButton.vue
- frontend/components/Players/DraggableQueue.vue
- frontend/components/Players/TrackList.vue
- frontend/nuxt.config.ts
- frontend/pages/library/_viewId.vue
- frontend/plugins/vue/directives.ts
* Add a transition when switching the text color between non playing tracks and the playing track.
* Disable Play and shuffle buttons in library view when the view is loading or there are no items.
* Fix item jumping in the draggable queue
* Fix animation quirk when the queue was opened and closed too fast by clearing the timeout during the DOM nodes destroy process.
* Current playing item in queue has now bold text.
* Queue is automatically scrolled into the currently playing item (related to #962)
* Fix item images being blurred on all queue changes in queue manager.
> Queue manager improvements

- frontend/components/Buttons/PlayButton.vue
- frontend/components/Item/ItemMenu.vue
- frontend/components/Players/DraggableQueue.vue
- frontend/components/Players/PlayerManager.vue
- frontend/locales/en-US.json
- frontend/package.json
- frontend/plugins/store/watchers/playbackManager.ts
- frontend/store/playbackManager.ts
- frontend/tsconfig.json
- package-lock.json
* Move MediaSession API handling to playbackWatcher
* Improve context menu in queue manager (based on comments in #1753)
* All "Play Next" options will, by default, append the item(s) to the next position in queue, but if some items already exist in the queue, they will be moved (not added again, so duplicates can only be made by using the "Add to queue" option).
_For current playing item_
_For other items_
> feat(playback): improve queue options and minor refactor to player manager

- .github/workflows/unstable.yml
This is needed to avoid previous builds overwriting a more recent build that was quicker to finish.
> feat: cancel previous unstable actions when new one comes in

- frontend/components/Layout/HomeSection.vue
- frontend/components/Layout/Navigation/NavigationDrawer.vue
- frontend/pages/index.vue
- frontend/plugins/store/watchers/auth.ts
- frontend/store/homeSection.ts
~~Inefficient fix to a situation where the array was never falsy so it never awaited for it to fetch.~~
~~It's inefficient cause the method is fetched 3 times across the app, and on this specific page it'll fetch every time if the user doesn't have views.~~
~~What could be done is that:~~
~~1. the store is fetched by default by the app once so that others aren't expected to fetch it~~
~~2. convert parts of the app using it to be reactive (this part in this file isn't for instance)~~
* moved the front page home sections logic to a getter to be reactive to the store changes
* nav drawer libraries were already reactive but it manually fetched them still
* fetch the user views at authentication (remembered or not)
* removed the homesection manual "libraries" setup to a getter of the userviews
> fix: missing home sections

- frontend/components/Item/MediaStreamSelector.vue
Fix to a situation where a Movie/Episode with no default video track has no default set in the Item UI
[1779](https://github.com/jellyfin/jellyfin-vue/issues/1779)
> fix: Movie/Episode with no default video track fix

- .github/workflows/automation.yml
- .github/workflows/code_quality.yml
- .github/workflows/deploy.yml
- .github/workflows/job_messages.yml
Check in pull request checks if all the commits of a PR comply with the conventional commits specification, in order to enforce our [contribution guidelines](https://github.com/jellyfin/jellyfin-vue/blob/master/CONTRIBUTING.md)
Also added concurrency keys to the automation workflow and a few style improvements to our workflow files.
> ci: check compliance with conventional commits

- frontend/components/Layout/Artist/ArtistTab.vue
- frontend/locales/en-US.json
- frontend/pages/artist/_itemId/index.vue
- frontend/store/index.ts
Added method to show Albums, EPs, and Singles separately from complete discography.
I'm not a Vue dev, so I might have done things wrong. I wanted the breakpoints between Album/EP/Single to be configurable to a user's preference in the future if desired, so it's stored in a state store so it's not just hardcoded.
Right now it defaults to showing the Albums only if it discovers at least one release that's of Album length.
> Added method to show Albums, EPs, and Singles separately

- .github/renovate.json
Tauri dependencies are updated alongside the frontend ones. This commit separates them, while also not separating major and minor.
CI dependencies are also separated from major and minor updates.
> ci: separate renovate config for Tauri

- frontend/components/Item/MediaInfo.vue
This removes the useless decimals in media ratings to 1 decimal.
> feat: fix rating decimals on media rating

- .github/renovate.json
- tauri/Cargo.lock
This fixes some Dependabot alerts.
Automated lockfile maintenance should prevent those from happening in the future (or be less common).
> chore(ci): add lockfile maintenance to renovate and update Cargo lockfile

- .github/workflows/codeQL.yml
- .github/workflows/code_quality.yml
With all the PRs that are now being targeted at #1812, not having checks on them is a major inconvenience.
> ci: run CI checks on PRs that are not targeted to master

- frontend/src/components/System/AboutLinks.vue
- frontend/src/pages/settings/index.vue
v-list-item-group seems to be not available anymore in Vuetify 3. I can't find any information on it. We use v-item-group (not v-list-group which was causing the settings not to show up) instead.
We use templates with v-slot:prepend and v-slot:append to place the icons correctly before or behind the actual settings name and description.
> fix: Use VItemGroup to display settings list again

- frontend/src/components/Layout/VirtualGrid/pipeline.ts
When the available virtual buffer is bigger than the amount of items that we want to show, the incorrect slice bounds were used. When the length of items is less than whatever buffer we had set, no virtual scrolling is used at all.
> fix(virtual-grid): slice bounds

- frontend/plugins/nuxt/browserDetectionPlugin.ts
Web OS User agent is actually with a Web0S (with a zero) for some reason. This PR fixes this.
Find reference in LG docs here 
https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine
> Fixed webos useragent

- frontend/src/components/Buttons/SortButton.vue
- frontend/src/components/Buttons/TypeButton.vue
This fixes the type and sort buttons at the top of the library page.
Type button functionality seems to work fine.
Sort functionality acts weird on my library. Sorting seems random.
Probably something wrong with the logic behind it.
Because we cannot use `v-list-item-group` anymore, we cannot use the index of the selected item anymore. We pass on the actual selected item when emitting the change event. For the labels in the button and list to work, some testing with a ternary operator needs to be done. Not the prettiest, I admin. If you have a tidier solution, please let me know and I will implement it.
> Fix type and sort buttons

- frontend/src/components/Buttons/FilterButton.vue
This fixes the Filter button. At least the UI part. 
A couple of problems:
- Filtering itself works (you can see the number of displayed items updating, 280 in the screenshot), but the displaying of filtered items acts weird sometimes. In the screenshot, underneath "280", you can see a small part of the title of one of the items.
- After applying a filter, I cannot change page without fully refreshing the full app. Not sure what's causing that. Help welcome.
- I wanted to use `dense` lists, like before. That prop has been removed in favor or `density="compact"`. But that does not seem to change anything. I compared the list of filters with the one in `master` branch and the difference is negligible, although more compact would be better if you ask me.
| master  | this branch  | 
|---|---| …
> fix: FilterButton

- frontend/index.html
- frontend/package.json
- frontend/src/assets/styles/global.scss
- frontend/src/main.ts
- package-lock.json
OverlayScrollbars made loading pages with a lot of items in a VirtualGrid unusable for a lot of time on Safari iOS. The page would stutter a lot and be impossible to scroll for tens of seconds.
Removing OverlayScrollbars makes the page be available instantaneously but remove the standardisation of the scrollbar.
This PR applies a simple styling on Webkit scrollbars to be less wide and with a darker background. It'd be good to use the Vuetify's surface theme color to style the background with the theme's color, but it needs to be done in JS cause the CSS variable isn't available to the root CSS scope.
> Remove OverlayScrollbars

- frontend/src/components/Item/RelatedItems.vue
Background color set to transparent and prepend the avatar to the name of the related item
> fix: relatedItems background color and avatar prepend

- frontend/src/components/Item/ItemMenu.vue
- frontend/src/components/Item/Metadata/ImageEditor.vue
- frontend/src/components/Layout/AppBar/Buttons/TaskManagerButton.vue
- frontend/src/components/Layout/VirtualGrid/pipeline.ts
- frontend/src/components/Skeletons/SkeletonCard.vue
- frontend/src/components/Skeletons/SkeletonHomeSection.vue
- frontend/src/pages/index.vue
- frontend/src/pages/item/_itemId/index.vue
- frontend/src/store/items.ts
- frontend/src/store/playbackManager.ts
- frontend/src/utils/data-manipulation.ts
- frontend/src/utils/items.ts
Removes unnecessary `as` casts, along with a few other typing updates. Mostly low-hanging fruit.
See #1869 for original effort on master branch.
Some of my own notes from going through `as` casts in code base:
1. `as` casts are being used to type component data structures, rather than using interfaces. I'll look into converting these next.
2. `as` casts are being used as not-null assertions fairly often. This should either be changed to actual not-null-assertions operators (`!`), which are still not ideal and are currently sent to error with linting, or actually have null checks performed. This is difficult because of the DTO types from the api.
3. At the moment, there are likely too many `as` casts for a linting rule to be useful, but we should consider adding them as these narrow down.
> style: remove unnecessary as casts

- frontend/src/components/Layout/Carousel/Carousel.vue
- frontend/src/components/Layout/Carousel/CarouselProgressBar.vue
- frontend/src/components/Layout/Carousel/Item/ItemsCarousel.vue
- frontend/src/components/Layout/Carousel/Item/ItemsCarouselTitle.vue
- frontend/src/layouts/default.vue
- frontend/src/pages/index.vue
- frontend/src/store/userLibraries.ts
- frontend/src/utils/items.ts
Due to reactivity bugs (which need to be solved for the index to properly load, as the content might change after the Carousel component is mounted), the remaining Carousel components are migrated to Composition API.
> perf(vue3): improve index loading times by only blocking navigation at login

- frontend/src/components/Buttons/SubtitleSelectionButton.vue
- frontend/src/components/Item/ItemMenu.vue
- frontend/src/components/Item/Metadata/DateInput.vue
- frontend/src/components/Item/Metadata/ImageEditor.vue
- frontend/src/components/Item/Metadata/ImageSearch.vue
- frontend/src/components/Item/Metadata/MetadataEditor.vue
- frontend/src/components/Item/PeopleList.vue
- frontend/src/components/Item/RelatedItems.vue
- frontend/src/components/Layout/Carousel/Carousel.vue
- frontend/src/components/Playback/DraggableQueue.vue
- frontend/src/components/Skeletons/SkeletonCard.vue
- frontend/src/components/Skeletons/SkeletonHomeSection.vue
- frontend/src/pages/library/_viewId.vue
- frontend/src/pages/metadata/index.vue
- frontend/src/pages/settings/apikeys.vue
- frontend/src/pages/settings/devices.vue
- frontend/src/pages/settings/index.vue
- frontend/src/pages/settings/logs-and-activity.vue
- frontend/src/pages/wizard.vue
- frontend/src/plugins/remote/auth/index.ts
- frontend/src/plugins/remote/axios/index.ts
- frontend/src/store/items.ts
- frontend/src/utils/images.ts
- frontend/src/utils/supported-features.ts
Some more cleanup commits stacked on each other.
Goals that this PR builds towards:
1. No more `@ts-expect-error` exceptions - these can be avoided by typecasting where necessary. It's less safe to completely ignore any static compiling error on a line than to resolve an error with a typecast. Linting rule coming in future PR.
2. No more unnecessary `as` casts - linting rule incoming in later PR once these are all removed.
3. `typecheck` script runs successfully
Recommend reviewing the changes commit by commit
> chore: more cleanup

- frontend/locales/en-US.json
- frontend/package.json
- frontend/src/App.vue
- frontend/src/assets/styles/global.scss
- frontend/src/components/Buttons/PlayButton.vue
- frontend/src/components/Buttons/PlaybackSettingsButton.vue
- frontend/src/components/Buttons/QueueButton.vue
- frontend/src/components/Buttons/SubtitleSelectionButton.vue
- frontend/src/components/Buttons/TooltipButton.vue
- frontend/src/components/Item/MediaStreamSelector.vue
- frontend/src/components/Playback/OsdPlayer.vue
- frontend/src/components/Playback/PiPVideoPlayer.vue
- frontend/src/components/Playback/PlayerElement.vue
- frontend/src/composables/index.ts
- frontend/src/composables/use-router.ts
- frontend/src/layouts/default.vue
- frontend/src/pages/playback/video/index.vue
- frontend/src/plugins/remote/axios/index.ts
- frontend/src/store/index.ts
- frontend/src/store/playbackManager.ts
- frontend/src/store/playerElement.ts
- frontend/vite.config.ts
- package-lock.json
> Implement video player in Vite branch

- .github/workflows/automation.yml
- .github/workflows/codeQL.yml
- .github/workflows/code_quality.yml
- .github/workflows/job_messages.yml
- .github/workflows/release.yml
- .github/workflows/unstable.yml
Currently all builds are failing the `Lint` and `Typecheck` (and other) steps due to an error with 
setting up the node environment, `ENOWORKSPACES`. From the Lint logs for recent PRs (like #1881):
These errors are because the npm cache option doesn't work with npm workspaces - try running `npm config get cache` locally to confirm this. This PR removes the github actions cache option to allow the github action workflows to run.
The jobs still fail now because of linting and type checking errors, but the steps actually run to completio.
This should help monitor how PRs increase/decrease lint rule and type checking violations.
> fix: fix failing github action setup

- README.md
* Make the description framework agnostic, so we don't need to update it in case we switch our desktop app bundler (for example)
* Add better description for end users. We were too developer centric
* Add links to Wiki for all the pieces that are more susceptible of evolving
* Add some clarification about how jellyfin-vue works (add a note about jellyfin-web too) in regards to privacy, since by what I read on Reddit, many people assume the connections are not direct between their devices and the target Jellyfin server.
* Made that privacy note really agnostic for how the client might be served/distributed in the future (but hopefully I did it in a clear way)
* Clarify the "Getting started" and "Running a production build sections"
> chore: post-Vue3 merge README

- frontend/src/pages/item/_itemId/index.vue
Fixes #1931
NB: One problem I can see here is we are not resetting index of audio, video and subtitles. So, there might be a chance to have empty values while switching across versions here. I'm fairly new to vue, If you have any suggestion on how can I fix that, please let me know :sweat_smile:
> fix: version selector not working

- frontend/src/components/Layout/Carousel/Item/ItemsCarouselTitle.vue
This removes redundant text that could also be mixed up between metadata and application languages (before and after):
> ui: only use episode name as subtitle

- frontend/package.json
- frontend/vite.config.ts
- package-lock.json
- tauri/tauri.conf.json
This should work out of the box for clients that have been running already, but the service worker will be permanent to them. all data associated with the site must be cleared for it to be completeley gone.
> fix: reloading after client changes

- frontend/locales/en-US.json
- frontend/package.json
- frontend/src/components/Item/MediaStreamSelector.vue
- frontend/src/components/System/LocaleSwitcher.vue
- frontend/src/composables/use-datefns.ts
- frontend/src/plugins/i18n.ts
- frontend/src/store/clientSettings.ts
- frontend/src/utils/i18n.ts
- frontend/types/global/plugins.d.ts
- frontend/vite.config.ts
- package-lock.json
Beforehand, we used https://github.com/ihmpavel/all-iso-language-codes to get translations of the languages we need. That module generated the locale names using Node.JS Intl API, as seen here: https://github.com/ihmpavel/all-iso-language-codes/blob/5a2cdb56d2662995db27ef4498cb71abbf13efee/scripts/generate.ts#L66
The Intl.DisplayNames API is widely supported according to MDN docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames Thus, it made sense to get the info we need at runtime. Also, all the language code translation is probably going to be miles better and up-to-date to Unicode standards than whatever library we use, which will always rely on updates. This movement also reduces bundle size by a lot!
Additionally, to reduce the …
> refactor: use browser internationalization APIs and resolve locales at build time

- frontend/src/components/Item/Metadata/MetadataEditor.vue
Using computed Tagline instead of `metadata.Taglines` since that is a list.
Honestly, a weird choice to use list instead of just a normal string (which exist as `Tagline` but not used?).
> fix: unable to submit metadata edit

- frontend/locales/en-US.json
- frontend/src/components/Dialogs/ConfirmDialog.vue
- frontend/src/components/Item/ItemMenu.vue
- frontend/src/components/Item/Metadata/RefreshMetadataDialog.vue
- frontend/src/components/Layout/AppBar/Buttons/TaskManagerButton.vue
- frontend/src/plugins/vuetify.ts
- frontend/src/utils/items.ts
- frontend/types/global/components.d.ts
- frontend/types/global/routes.d.ts
Split from the following PR: https://github.com/jellyfin/jellyfin-vue/pull/1951
> feat: add Refresh Metadata context menu to anything other than library

- frontend/src/assets/styles/global.scss
The last 2 major browsers without overlay scrollbars (Microsoft Edge and Google Chrome) are already adding flags to their experimental settings to allow users to use native overlay scrollbars.
Native overlayed scrollbars are much better than whatever styling we use. Plus, styled scrollbars removes the overlay scrollbar altogether, as there's no way to tell the browser to prefer them instead of our own (which would be nice for backwards compatibility)
Firefox have OverlayScrollbars in all desktop platforms already. Mobile platforms had them since day one.
See also this: https://chromestatus.com/feature/5693137379917824
> feat: no styled scrollbars

- frontend/src/components/Playback/TrackList.vue
Closes #1950
Was originally part of #1962 but since the recent item-menu changes, it would be better if this was fixed sooner.
Without this fix, music album item menu would look like this:
> fix: wrong item in track list for item menu

- frontend/src/components/Item/ItemGrid.vue
- frontend/src/components/Item/MediaInfo.vue
- frontend/src/components/Layout/Carousel/Item/ItemsCarouselTitle.vue
fix #1924
* Display 12 cards on `xxl` screens (>1200px width) on the library page
* Slightly bigger font on home carousel titles. I haven't increased much due to text already be in rem and those handled by the browser.
> ui: more library cards on big screens + slightly bigger font on home carousel

- tauri/Cargo.lock
- tauri/Cargo.toml
serde was automatically added when scaffolding the Tauri project. However, it doesn't seem necessary (at least for now that we don't have intercommunication betwen the frontend and Tauri).
If it's necessary for inter-communication with the frontend in the future we can always add them back
> chore: remove unnecessary rust dependencies

- frontend/package.json
- frontend/src/components/Item/Identify/IdentifyDialog.vue
- frontend/src/store/clientSettings.ts
- frontend/src/store/items.ts
- frontend/src/store/playbackManager.ts
- frontend/src/store/playerElement.ts
- frontend/src/store/taskManager.ts
- frontend/src/store/userLibraries.ts
- package-lock.json
Using the native method will always be better (and probably faster) than using a 3rd party library
Reference from: https://github.com/jellyfin/jellyfin-vue/pull/2047#issuecomment-1596300769
> perf: replace klona with structuredClone

- frontend/locales/en-US.json
- frontend/src/assets/styles/global.scss
- frontend/src/components/Buttons/LikeButton.vue
- frontend/src/components/Buttons/MarkPlayedButton.vue
- frontend/src/components/Item/Card/Card.vue
- frontend/src/components/Item/ItemMenu.vue
- frontend/src/components/Item/WatchedIndicator.vue
- frontend/src/components/Layout/AppBar/Buttons/TaskManagerButton.vue
- frontend/src/components/Layout/Carousel/CarouselProgressBar.vue
- frontend/src/components/Layout/Images/Blurhash/BlurhashCanvas.vue
- frontend/src/components/Layout/Images/Blurhash/BlurhashWorker.ts
- frontend/src/components/Layout/TimeSlider.vue
- frontend/src/components/Playback/PlayerElement.vue
- frontend/src/components/Playback/UpNext.vue
- frontend/src/pages/playback/video/index.vue
- frontend/src/store/playbackManager.ts
- frontend/src/store/taskManager.ts
- frontend/src/utils/items.ts
- frontend/src/utils/time.ts
- frontend/types/global/components.d.ts
* Fix multiple menus opened in queue
* Clear Blurhash cache on logout
* Convert Blurhash cache to a map
refactor: playbackManager
* Move item runtime to PlaybackManager
* Organize watchers by scope
* Better handle concurrency on setCurrentMediaSource when switching audio tracks really fast, discarding stale data
* Remove unused properties from state
* Remove "lastItemIndex" in favor of a watcher that tracks the currentItem Id changes and reports playback changes
* Attempt to send playback stopped status to server when closing tab (fix #1781)
Requires a vueuse release that includes this PR: https://github.com/vueuse/vueuse/pull/3072 (labeling blocked because of that)
fix: handle undefined media url
In playbackManager, we set the currentMediaSource url to undefined to prevent the previous …
> refactor: QoL improvements

- frontend/src/components/Layout/AppBar/Buttons/TaskManagerButton.vue
The first menu item in TaskManagerButton hided by app-bar
- Before
- After
> fix: TaskManagerButton hide by app-bar

- frontend/src/store/playbackManager.ts
- frontend/src/store/userLibraries.ts
We shouldn't put artificial limits to what we want to retrieve from the server based on the performance the server has for a particular request. Server's performance is not a thing client's need to take care about, is solely server's responsability
When the new API is designed, we should follow a GH-like approach, where requests that might be long-running for large data lists are forced to use pagination and request cursors.
More info at https://github.com/jellyfin/jellyfin-next/discussions/7
This commit also fixes #2015
**Marking as draft since I'm not sure if the `userLibraries` limits are because a UI/UX design decision**
> refactor: remove apparent artificial limits

- frontend/locales/en-US.json
- frontend/src/components/Buttons/SortButton.vue
I added two more (missing) sort options to the library page, specifically `DateCreated` and `CommunityRating`.
Closes #1959
> Add more library sort options

- frontend/src/components/Playback/MusicVisualizer.vue
Output was doubled since the visualizer connects to the speakers by default. See https://github.com/hvianna/audioMotion-analyzer#connectspeakers-boolean for reference.
> fix: music visualizer volume change

- Dockerfile
Given Alpine doesn't use glibc, and LightningCSS
doesn't provide a `lightningcss-linux-arm-musl` target,
build fails for `linux/arm` platform. Switch to Debian, since we don't
need the build container to have alpine's small footprint and
this might resolve other incompatibilities in the future.
Reported upstream at https://github.com/parcel-bundler/lightningcss/issues/563
What this commit does:
* Switch nginx to stable version instead of mainline (keeping it in alpine since
we don't have any requirement after the frontend is built).
* Switch from `node:18-alpine` to `node:18`, which also saves us the extra
layer of installing git, ending up being much faster since we don't have to run
`apt update` either to update the apt index (the extra pull bandwidth
required to pull a bigger image is …
> fix(ci): docker build

- frontend/locales/en-US.json
- frontend/src/components/Item/Identify/IdentifyDialog.vue
- frontend/src/components/Item/ItemMenu.vue
- frontend/src/components/Item/MediaDetail/MediaDetailDialog.vue
- frontend/src/components/Item/Metadata/MetadataEditor.vue
- frontend/src/components/Item/Metadata/MetadataEditorDialog.vue
- frontend/src/components/Layout/AudioControls.vue
- frontend/src/pages/item/_itemId/index.vue
- frontend/src/store/playbackManager.ts
- frontend/src/utils/items.ts
The following context menu has been adjusted for multiple media streams:
- Delete (should correctly delete the selected stream)
- Media Info (hide the stream selector if media index is provided)
- Metadata editor (should correctly show/edit the selected stream)
The multi-supported context menu would only show on the following:
- Item page
- Playback bar (audio mode)
Anything outside just default to the first media source.
> feat: support multiple streams for item menu

- .devcontainer/devcontainer.json
The Microsoft image includes some dependencies installed globally, which increases load times and storage space
for Codespaces unnecessarily.
It also let us debug the Dockerfile more easily in case it's needed since we share the same base image with it.
> chore(codespaces): switch to node as base image

- frontend/src/store/playbackManager.ts
Stream URLs are at /Videos/ not /Video/.
5e33e8e0fbe465971c92074a366a5eefa2feb9cb introduced this regression, by replacing `'Videos'` with `this.currentlyPlayingMediaType` which contains value `'Video'`.
This regression means that playing videos that have direct play available results in a 404, and the player hangs.
What has me quite confused is... this regression was introduced back in June, almost 4 months ago... how did nobody notice that playing *any* direct play movie/video was broken?
> Fix direct play stream url regression

- frontend/src/utils/external-config.ts
- frontend/vite.config.ts
By setting the [`base` option ](https://vitejs.dev/config/shared-options.html#base) to `./` we enable _relative_ loading of assets and replace the current _absolute_ path resolution. This, along with removing the leading `/` when loading the external config via fetch allows the client to be installed in a sub-path at any level of nesting.
This **does not** require any changes to the env file, or any other changes by the user.
> Fixes #2085 - Allow installation in a sub-path

- frontend/src/assets/styles/global.scss
There is no point in having elastic overscroll since when we have proper data fetching we will have all the updates handled by the websocket.
It also requires proper thinking and testing when introducing UI features and not all developers have a touchpad to notice this behaviour properly
(it went unnoticed for so long in fact).
Main reason is the UI is buggy for it.
> fix: disable eslastic overscroll

- frontend/vite.config.ts
- packaging/docker/Dockerfile
git was not included in node's slim image, hence there was no commit hash hardcoded in the resulting client
> ci(dockerfile): fix missing commit hash

- README.md
In 2016, CloudFlare changed their name to Cloudflare (lack of capital F). See blog: https://blog.cloudflare.com/time-for-an-update/
This PR is just a simple, one-letter fix for the README to match this branding. Not important really but I thought I'd correct it since I noticed it.
> Update CloudFlare -> Cloudflare in README.md

- frontend/index.html
- frontend/src/splashscreen.ts
- frontend/src/store/clientSettings.ts
- frontend/vite.config.ts
This will ease the maintenance burden of that code by allowing us to use the same tooling we use for the rest of the code (type-checking, eslint, etc)
while also allowing us to use npm dependencies (like destr in this case), which could be
helpful in the future.
> refactor(splashscreen): emit splashcreen code with rollup instead of embedding in index.html

- frontend/src/pages/item/[itemId].vue
When viewing an episode/item page, the MediaSources watcher does not trigger instantly, causing the Video, Audio, and Subtitles dropdowns to not show until the MediaSources are updated again.
Watchers by default are lazy, when in this instance it should be eager and trigger when it attaches.
Adding the immediate tag makes this watcher eager, resolving the issue.
> fix: Add immediate tag to MediaSources watcher

- README.md
The current command, `docker run -d -p 8080:80 ghcr.io/jellyfin/jellyfin-vue`, simply prints
```
docker: Error response from daemon: manifest unknown.
```
As long as there’s no latest (stable) release the “default” branch should point to unstable.
> chore(readme): add :unstable to docker run

- frontend/src/components/Item/Card/Card.vue
- frontend/src/components/Item/ItemGrid.vue
The card component was rendering ItemMenu, PlayButton and LikeButton at once,
even when not being displayed on screen.
Now, they're just rendered when necessary.
Memory usage went from ~78 MB to ~35 MB consistently in one of my libraries' view.
With Card rendering less components, we can render faster in libraries, so displaying less components equals to the same experience we had previously with increased buffers
> perf: improve Card rendering performance

- frontend/public/config.json
- frontend/src/components/Forms/AddServerForm.vue
- frontend/src/components/Forms/LoginForm.vue
- frontend/src/pages/server/login.vue
- frontend/src/plugins/remote/index.ts
- frontend/src/plugins/router/middlewares/login.ts
- frontend/src/utils/external-config.ts
- packaging/docker/contents/setup.sh
* Fix the users being redirected to the 'Add Server' screen (#2117) on first start
* Allow to disable the server selection screen with a new key: 'allowServerSelection'
WARNING: When it's false, the following situations will leave the client in an endless loading state if:
- This is enabled and no default servers have been provided
- The first server in the 'defaultServerURLs' array can't be reached
> feat(auth&config): add 'allowServerSelection', fix server wait on boot

- frontend/src/components/Forms/LoginForm.vue
This is a very, very simple edit. As the icon is added as `inner-icon`, the icon event should also be `click:append-inner`.
> fix: correctly trigger showPassword

- frontend/src/components/Playback/PlayerElement.vue
- frontend/src/pages/playback/video.vue
- frontend/src/store/playerElement.ts
* The video was not centering nor stretching when necessary
* By default, stretch is disabled and the video keeps it's proportions
* This fix also simplifies the styles
Fix #2255
> fix(video): styles

- frontend/src/pages/playback/video.vue
-Fixed video player taking monitor height instead of window height.
-Fixed video player not centering content less large then the window (4:3 video)
added more info on a new comment in #2255
further fix for #2257
> Fixed height and width issues with video player

- frontend/src/components/lib/JImg.vue
Fixed images that where stretched with object-fit:cover so that they keep the original image ratio
> Fixed stretched actor images

- frontend/.eslintrc.cjs
- frontend/src/components/Layout/Images/Blurhash/BlurhashCanvas.vue
- frontend/src/components/Layout/Images/Blurhash/BlurhashWorker.ts
[Match the values I used for Jellyfin Web back in the day](https://github.com/jellyfin/jellyfin-web/blob/master/src/components/images/imageLoader.js#L52-L56)
> perf: reduce default blurhash quality

- frontend/src/components/Layout/Images/Blurhash/BlurhashImage.vue
Needed so item changes pass properly through all the loading states of JImg, but window size changes does it only on first load.
> fix(BlurhashImage): proper use of JImg once prop

- frontend/src/components/lib/JImg.vue
The bug in Safari was due to an incorrect usage of the `rel` attribute.
Fixes #2291
> fix(JImg): preload in Safari

- .github/renovate.json
- frontend/package.json
- frontend/src/components/Layout/AudioControls.vue
- package-lock.json
When all the queue is finished, the footer gets stuck in the middle of the page. Vuetify changed something that makes Vue's v-if not work properly.
Given I'm going to remove Vuetify from the app sooner than later, I'm removing it from renoavet dependency updates
> fix(AudioControls): downgrade Vuetify to fix persistent footer

- .github/workflows/package.yml
Follow-up of https://github.com/docker/build-push-action/issues/1151
> ci(docker): don't upload build record artifacts

- README.md
I want to make it very clear in the README what the Vue client is and what it's goals are vis-a-vis the project as a whole, to avoid any mistaken impression about where it's at.
For technical reasons, mostly Vue.js dropping support for "old" browsers, Jellyfin Vue can never reasonably replace the main web client. So, it will always be at most an alternative client.
This PR ensures that this is now spelled out clearly at the top of the README.
> Update README to reflect actual status

- frontend/src/plugins/router/middlewares/login.ts
Block server addition and selection when disallowed by config.
Updated the server addition and selection logic to respect the `allowServerSelection` configuration setting.
Verified that server addition and selection are blocked when `allowServerSelection` is false.
> fix(serverAdd): block server addition and selection when disallowed by config

- frontend/package.json
- frontend/src/store/playback-manager.ts
- frontend/src/store/player-element.ts
- frontend/src/utils/playback-profiles/subtitle-profile.ts
- package-lock.json
**Changes**
This PR allows the client to request and render native PGS subtitle streams without transcoding. PGS is a graphical subtitle format. The subtitles are rendered locally by the client on-top of the video element.
This adds a new dependency [libpgs-js](https://github.com/Arcus92/libpgs-js). I just created this library for the Jellyfin project. If desired, you can fork it into the https://github.com/jellyfin domain.
**Related Pull Request (backend):** https://github.com/jellyfin/jellyfin/pull/12056
**Related Pull Request (web):** https://github.com/jellyfin/jellyfin-web/pull/5688
> Add support for native PGS subtitle rendering without transcoding

- .github/workflows/__quality_checks.yml
- frontend/package.json
- frontend/scripts/plugins/analysis.ts
- frontend/vite.config.ts
- package-lock.json
* The dpdm dependency was used just for checking circular dependencies in the bundle. However, it was not perfect, not analyzing the real bundle, but the source files. We were just leveraging Rollup's (Vite internal bundler) warnings for that already when analyzing the bundle, which always gave us the real information. Now, `analyze` consists in 2 different commands (analyze:bundle for the bundle and analyze:cycles for finding cycles)
* The npm commands have been grouped by scope
* Extracted analyze Vite commands to a plugin, so the main config is cleaner
> refactor: remove dpdm, npm commands, bundle analysis

- frontend/src/App.vue
- frontend/src/components/Layout/AppBar/AppBar.vue
- frontend/src/composables/apis.ts
- frontend/src/pages/item/[itemId].vue
- frontend/src/pages/library/[itemId].vue
- frontend/src/plugins/remote/sdk/index.ts
- frontend/src/plugins/router/index.ts
- frontend/src/store/index.ts
Vue 3.5 implements pausable effects which are super useful for finally getting this fixed.
This is currently blocked by https://github.com/vuejs/core/issues/11812
> fix: content fetching when navigating

- frontend/index.html
- frontend/scripts/plugins/chunking.ts
- frontend/src/components/lib/JSplashscreen.vue
- frontend/vite.config.ts
Code-split the application (but without lazy loading, aka dynamic imports aka async modules, so all the assets are loaded on app load, not when requested: this is needed for ensuring an smooth experience over slow networks)
Lighthouse performance score went from 66 to 77
There's still a lot of work to do, but this is a good start
> perf: code-split the application

- frontend/src/plugins/router/index.ts
Related Issue: [#2403](https://github.com/jellyfin/jellyfin-vue/issues/2403)
**Summary**
This merge request resolves a navigation issue where users were unable to traverse the entire navigation history using the back button in the application's sidebar. The problem stemmed from overriding the router.back method with router.replace, which disrupted the history stack and prevented Vue Router from accurately tracking the history length.
> fix(router): don't use replace on every route when going back

- frontend/src/App.vue
- frontend/src/components/Item/Card/GenericItemCard.vue
- frontend/src/components/Item/ItemGrid.vue
- frontend/src/components/Item/ItemMenu.vue
- frontend/src/components/Item/Metadata/ImageEditor.vue
- frontend/src/components/Layout/AppBar/AppBar.vue
- frontend/src/components/Layout/Carousel/Item/ItemsCarouselTitle.vue
- frontend/src/components/Layout/Navigation/NavigationDrawer.vue
- frontend/src/components/Layout/SettingsPage.vue
- frontend/src/components/Layout/SwiperSection.vue
- frontend/src/components/lib/JTransition.vue
- frontend/src/components/lib/JView.vue
- frontend/src/composables/apis.ts
- frontend/src/layouts/server.vue
- frontend/src/pages/server/select.vue
- frontend/src/store/index.ts
- frontend/src/store/keys.ts
This also fixes some data changes that happened hile navigating like:
* When using search and clicking on an item, the "No results available" message would appear
* When navigating to a liibrary, the transparency effects of the navdrawer or appbar would match those of the entering route.
> perf: pause patching while navigating

- .github/workflows/__package.yml
- packaging/docker/Dockerfile
- packaging/docker/contents/docker-entrypoint.sh
- packaging/docker/contents/nginx.conf
- packaging/docker/contents/postunpack.sh
- packaging/docker/contents/setup.sh
This allows to simplify the custom entrypoints command a little bit
> chore(docker): trim more the image, always run setup

- frontend/src/plugins/router/middlewares/login.ts
It's been a while since I contributed, so I'm kinda new again here and I don't know exactly what I'm doing.
However as far as my testing goes, this seemed to work. However I didn't verify if subtitles still work. But I imagine it should.
the div class=uno-my-auto div caused the media element to not realize it had more room to fill. Removing it let the parent elements css classes become effective. It still seems to work as expected in the mini version of the player.
This could also cause the stretch option to do something, however I'm not sure why anyone would even want this functionality (non-aspect-preserving stretch to fit - if it works). I would probably recommend removing it for simplicity... That is not part of this PR however :)
> fix: /server/login with disabled server selection

- frontend/src/components/Playback/MiniVideoPlayer.vue
- frontend/src/pages/playback/video.vue
not too much more to say.
closeOnBack according to vuetify documentation:
> Closes the overlay content when the browser's back button is pressed or `$router.back()` is called, cancelling the original navigation. `persistent` overlays will cancel navigation and animate as if they were clicked outside instead of closing.
> fix: navigation out of video player - VOverlay was hijacking navigation

- frontend/src/store/playback-manager.ts
- frontend/src/utils/items.ts
Subtitles were using the MediaStream index to select what subtitles to play, rather than the TextTrack index.
This meant that the subtitles were playing incorrectly as it was taking into account the Video/Audio streams when selecting a subtitle.
E.G:
English 1
English 2
English (SDH)
Bulgarian
CZE
When selecting English 1, This plays the English (SDH).
When selecting English 2, This plays Bulgarian.
When selecting English (SDH), This plays CZE.
This is because the MediaStreams are:
Video
Audio
English 1
English 2
etc...
This PR refactors the subtitle selection code to set the Index and srcIndex to be based on the TextStream, instead of the MediaStream.
resolves #2519
> refactor: Update subtitle streams to use TextTrack indexes

- frontend/src/components/Item/Card/GenericItemCard.vue
- frontend/src/components/lib/JApp.vue
The `--j-color-background` was converted to rgb directly when being redeclared in JApp. However, it needed to be raw so it could be properly passed for the alpha.
Supersedes #2526
> fix(GenericItemCard): overlay background alpha

- frontend/src/pages/wizard.vue
@ferferga I'm sorry that the issue was not completely resolved in yesterday's PR. While I was addressing other issues today, I discovered that the initial position was not set to "Language and locale," but rather to "Administrator account." I initially thought that was the intended setting, but when I started a brand new service for testing, I found that the initial position was incorrect, so I made the necessary modifications.
> fix(wizard): fixed the issue with the initial position of the stepper.

- frontend/src/components/Layout/Navigation/CommitLink.vue
- frontend/types/global/components.d.ts
After the merge of #2539, the Docker builds from CI stopped working properly. However, local and Codespace builds (even locally built Docker images) still are working fine, so no idea what's going on. This PR is a playground to test stuff since it can only be reproduced in CI-produced artifacts. When the fix is found, this same PR is going to contain the fixes.
> fix: failing Docker images from CI

- frontend/src/composables/use-playback.ts
- package-lock.json
- packages/configs/src/lint/rules/typescript-vue.ts
- packages/tauri-runtime/README.md
- packages/tauri-runtime/entrypoint.ts
- packages/tauri-runtime/package.json
- packages/tauri-runtime/src/fullscreen.ts
- packages/tauri-runtime/tsconfig.json
- packages/tauri-runtime/vite.config.ts
- packaging/tauri/tauri.conf.json
Implements full window's fullscreen functionality inside @jellyfin-vue/tauri-runtime package
Supersedes #2503
> feat(tauri): implement fullscreen toggle functionality

- frontend/src/components/Layout/AppBar/Buttons/TaskManagerButton.vue
- packages/i18n/strings/en.json
Before:
After:
Because its called Library here, not Item: https://github.com/jellyfin/jellyfin-vue/blob/master/frontend/src/components/Layout/AppBar/Buttons/TaskManagerButton.vue#L79
> chore: fixed scanningItemInProgress text
